### ISSUE TITLE
Persistente connection

### ISSUE THREAD

**Issue by christian-aiko** [adrienverge/openfortivpn#251] opened 2018-02-09 11:55 UTC
It does not have reconnection functionality.
Don´t have a "always up" ....
It would be great functionality.

**Comment by DimitriPapadopoulos** [comment] 2018-02-09 12:58
Isn't this a duplicate of #190?

**Comment by christian-aiko** [comment] 2018-02-09 13:48
Yes...

=)

Thank You.

2018-02-09 10:58 GMT-02:00 Dimitri Papadopoulos Orfanos <
notifications@github.com>:

**Closed** 2018-02-09 15:02 UTC
