### ISSUE TITLE
Works with CLI arg for host, not in config

### ISSUE THREAD

**Issue by rask** [adrienverge/openfortivpn#129] opened 2017-05-24 10:42 UTC
When I define a gateway on the CLI as such:

    $ openfortivpn hostname.tld:443

The client connects properly.

But if I use the config file and define the same in there

    host = hostname.tld
    port = 443

The client timeouts on any connection attempts.

**Comment by mrbaseman** [comment] 2017-05-24 11:09
strange, I use the config file and it works for me. Can you run openfortivpn with option -v to see if it tries to read the config in the right place and what it loads from there? 

I also have a line for the username in my config. I think you need this also.

**Comment by rask** [comment] 2017-05-24 12:24
Yes, I have username, password, host, port, and the trusted-cert. Verbose output shows the config is loaded correctly with all of those, with the addition of the default empty `realm`.

    $ openfortivpn --version
    > 1.3.1

Checked out the latest stable(?) tag from source repo and bult from that. Let me know if a dev branch has a fix for this.

**Comment by mrbaseman** [comment] 2017-05-24 22:56
1.3.1 was tagged the day before yesterday, so it is nearly up to date with master (except for some changes to the README.md file)

To come back to your problem: openfortivpn takes the host:port tuple from the command line and overwrites the one which it has read from the config file before. Later it operates on the same data structures. So, if it works from the command line and not out of the file, it might possibly be a strange white space character heading or trailing the hostname or port. openfortivpn removes blanks and tab characters and treats newlines as line separator. If you for some reason have dos line endings, openfortivpn might take the carriage return as part of the FQHN.  
You could inspect your config file with a hex editor or rewrite a clean text file (maybe by echoing line by line and appending them). 
I hope this helps, otherwise I have to try if I can reproduce this somehow. If I can reproduce it, I can try to make the parser more robust.

**Comment by rask** [comment] 2017-06-07 10:54
I'll have to check the file more thoroughly. Thanks!

**Comment by mrbaseman** [comment] 2017-07-04 11:59
@rask did you find out what was causing this issue?

**Comment by rask** [comment] 2017-08-08 22:27
Sorry, been less reliant on VPN lately so have not had any time or chance to look into this any further. I'll add a reminder in case I manage to find a moment to investigate.

**Comment by jlchatha** [comment] 2018-04-19 18:47
I was able to reproduce and correct (white space issue).

**Comment by mrbaseman** [comment] 2018-04-19 19:17
@jlchatha So my suspicion was in the right direction. Could you give more details, or, since you write that you could correct the white space issue, prepare a pull request? That would be great, thanks in advance

**Comment by DimitriPapadopoulos** [comment] 2018-06-09 12:31
@jlchatha I understand you corrected a white space issue directly in the config file. Should perhaps we improve config file parsing? Can you show us where in the config file white spaces are causing a problem?

**Comment by jlchatha** [comment] 2018-06-09 16:06
Adrien,

I will attempt to replicate this weekend/early next week.

Apologies on the delayed response!

**Comment by jlchatha** [comment] 2018-06-12 16:40
I was not able to reproduce this in CentOS fresh install. Shot in the dark, copy and paste issues produced some sort of white space or other character. I will certainly update if I run in to this again. Apologies for the dropped ball here, should have a kept a copy of the broken config file. :/

Awesome package though. Much appreciated.

**Comment by DimitriPapadopoulos** [comment] 2018-06-12 16:44
@jlchatha Thank you very much for the feedback. Would you agree to close this issue for now? Of course you can reopen whenever you want if needed.

**Comment by jlchatha** [comment] 2018-06-12 16:46
Absolutely, close it!

**Closed** 2018-06-12 16:50 UTC
