### ISSUE TITLE
Feature Req : D-TLS support

### ISSUE THREAD

**Issue by goug71** [adrienverge/openfortivpn#854] opened 2021-02-18 18:49 UTC
FortiOS claims supports for D-TLS encapsulation with SSL-VPN, which is interesting to avoid tcp tunnel meltdown issue and maybe for performance in general. I have no information about encapsulation stack, but it might be worth digging for it...

**Comment by DimitriPapadopoulos** [comment] 2021-02-18 18:50
Duplicate of #473.

**Closed** 2021-02-19 10:21 UTC
Labels: duplicate
