### ISSUE TITLE
No DNS server are inserted into resolv.conf

### ISSUE THREAD

**Issue by secustor** [adrienverge/openfortivpn#577] opened 2020-03-20 14:03 UTC
As requested in https://github.com/adrienverge/openfortivpn/issues/503 I create new ticket for this issue. 
### Summary
After upgrading from `1.10.0-2` to `1.12.0-1` DNS Server are no longer inserted into `/etc/resolv.conf`. 

### Context
OS: Fedora 31 (fully updated) 
last working version: openfortivpn-1.10.0-2.fc31.x86_64
tested version: openfortivpn-1.12.0-1.fc31.x86_64

#### 1.12.0
```
DEBUG:  ip route add to 192.168.193.0/255.255.255.0 via 192.168.248.26 dev ppp0
DEBUG:  ip route add to 192.168.255.0/255.255.255.0 via 192.168.248.26 dev ppp0
DEBUG:  ip route add to 192.168.131.4/255.255.255.255 via 192.168.248.26 dev ppp0
INFO:   Adding VPN nameservers...
DEBUG:  resolvconf_call: /sbin/resolvconf -a "ppp0.openfortivpn"
INFO:   Tunnel is up and running.
DEBUG:  pppd ---> gateway (56 bytes)
```

#### 1.10.0 
```
DEBUG:  ip route add to 192.168.255.0/255.255.255.0 via 192.168.248.2 dev ppp0
DEBUG:  ip route add to 192.168.131.4/255.255.255.255 via 192.168.248.2 dev ppp0
INFO:   Adding VPN nameservers...
DEBUG:  Adding "nameserver 192.168.130.126" and "nameserver 192.168.130.91" to /etc/resolv.conf.
INFO:   Tunnel is up and running.
```

**Comment by DimitriPapadopoulos** [comment] 2020-03-20 14:18
Ah, my wrong, there are actually two distinct issues on _Fedora_:
1. interaction between _openfortivpn_ and _NetworkManager_, introduced with 1.11.0 and fixed in 1.12.0,
2. attempt to start `resolvconf` instead of modifying `/etc/resolv.conf`, introduced in 1.12.0

And indeed you're experiencing issue 2. I'm sorry I asked you to open a new issue, I'll close it as a duplicate of #503 if that's OK with you. Sorry again, I hope you're not mad at me...

The root problem is that _Fedora_ ships with a broken substitute for _resolvconf_. I think we have a fix in branch [mrbaseman/resolvconf_fix](https://github.com/mrbaseman/openfortivpn/tree/resolvconf_fix).

**Comment by DimitriPapadopoulos** [comment] 2020-03-20 14:23
Just to make sure, you could temporarily remove `/sbin/resolvconf` from the way:
```
sudo mv /sbin/resolvconf /sbin/resolvconf.bak
```
Then _openfortivpn_ should work.

Bacause `/sbin/resolvconf` is broken on _Fedora_ I doubt it is needed. However if needed restore it with:
```
sudo mv /sbin/resolvconf.bak /sbin/resolvconf
```

**Comment by secustor** [comment] 2020-03-20 14:51
Hahah! Non I am absolutly not mad. The response time is amazing ^^

You are correct, removing the `resolvconf` file works for me. 
Thank you for your support.

**Comment by DimitriPapadopoulos** [comment] 2020-03-20 15:40
Indeed a duplicate of #503.

**Closed** 2020-03-20 15:40 UTC
Labels: duplicate

**Comment by DimitriPapadopoulos** [comment] 2020-03-20 17:22
This is a different issue from #503 after all:
* #503 is about the incompatibility between _NetworkManager-fortisslvpn_ and _openfortivpn_ 1.11.0. It should be fixed in recent _Fedora_/_CentOS_/_EPEL_ packages.
* #555 is about _openfortivpn_ 1.12.0 calling the broken `resolvconf` on _Fedora_.

This is a duplicate of #555, not of #503.
