### ISSUE TITLE
macOS updating /etc/resolv.conf has no effect 

### ISSUE THREAD

**Issue by nirdothan** [adrienverge/openfortivpn#724] opened 2020-05-21 09:01 UTC
On MacOS Catalina 10.15.4, openfortivpn updated dns resolver in `/etc/resolv.conf` however it seems that most processes (e.g. curl, ping, chrome - but not dig ) do not use this file to to locate the resolver IP, and  `scutil --dns` is the source.
When comparing  `scutil --dns` after connecting with openfortivpn Vs FortiClient, I see that with ForiClient, an entry is added to `scutil --dns` with the correct dns resolver IP, however openfortivpn does not add such an entry

**Comment by DimitriPapadopoulos** [comment] 2020-05-21 09:27
Duplicate of #534.

This should help in the meantime:
```
set-dns = 0
pppd-use-peerdns = 1
```

**Closed by DimitriPapadopoulos** 2020-05-21 09:27 UTC
Labels: duplicate
