### ISSUE TITLE
openfortivpn 1.14.1 not resolving DNS on fedora33

### ISSUE THREAD

**Issue by slartibart70** [adrienverge/openfortivpn#824] opened 2020-12-31 20:28 UTC
Hi,
i'm using openfortivpn 1.14.1 on fedora33, the vpn can be established, but i cannot reach any (remote) server by its DNS name. IP is working perfectly, but no name resolution.
Interestingly, the entries created by openforti in /etc/resolv.conf are taken into account by 'dig', for example, 'dig' can resolve the dns names to valid ip addresses.
But, ssh or a browser cannot.

I found something similar in a bugreport to sshuttle (see: https://github.com/sshuttle/sshuttle/issues/554) which had exactly the same problems.
According to this bugreport, the problem is systemd and 'split DNS' support.
They also showed some workaround i have not tried (yet)

Could you please take a look at this?

**Comment by slartibart70** [comment] 2021-01-01 20:24
Hi all,
my current workaround is to disable the systemd-resolved by replacing the symlink of /etc/resolv.conf (which points to the stub /run/systemd/resolve/stub-resolv.conf) with a static file.
Now, systemd-resolved is not responsible any more and the 'traditional' way of adding search or nameserver entries to /etc/resolv.conf works again.

As i said, a workaround for the time being, but a proper solution would be nice (handled automatically by openfortivpn).

Btw, you added a commandline-option to 1.13.x called '--use-resolvconf=<bool>'
The man page still references this option (also with a sample the config file) but it does not seem to be valid any more? (throwing error messages when using it)
Got it lost somewhere on the road to 1.14.x?
And, would it help in this case anyway?

**Comment by slartibart70** [comment] 2021-01-01 20:28
one more thing:
openfortivpn adds (see workaround above) nameserver and search entries to /etc/resolv.conf
BUT:
When closing openforitvpn, only the nameserver entries are removed,
the search entries stay put.... 
Smells like a bug?

**Comment by DimitriPapadopoulos** [comment] 2021-01-02 08:22
Yes, most of these issues seem well known. Substantial work is required to adapt to new routing/DNS backends (_systemd_) that have appeared in recent Linux distributions. Please send some information if you want to us to have a look at this issue:
https://github.com/adrienverge/openfortivpn/wiki#user-content-reporting-issues

The `--use-resolvconf=` option does work, it is simply disabled by the Fedora Packager because the `resolvconf` that ships with _systemd_ is broken:
https://src.fedoraproject.org/rpms/openfortivpn/blob/master/f/openfortivpn.spec#_28

**Comment by slartibart70** [comment] 2021-01-02 11:51
Just a question:
wouldn't it be sufficient to check for the destination of the symlink (/etc/resolv.conf)? (see also man systemd-resolved)
Depending on this, if we see that this is e.g. using the stub, then leave /etc/resolv.conf alone (don't add any entries) and just add some commands like this:
sudo systemd-resolve --interface ppp0 --set-dns 10.62.32.11 --set-domain company.net

I tried this with a single domain and it seems to work.
So maybe it's as easy as this with adding several of these commands like you do already when constructing the 'search' entry in /etc/resolv.conf?

**Comment by DimitriPapadopoulos** [comment] 2021-01-02 14:06
Yes, that's the spirit - but using D-Bus calls instead of running executables. I'm still seeing it as substantial work. If you want to contribute have a look at #600.

**Comment by DimitriPapadopoulos** [comment] 2021-01-03 21:05
If you send the contents of `/etc/resolv.conf` before/during/after VPN operation, we can try to infer what fails in your case.

**Comment by slartibart70** [comment] 2021-01-05 08:45
at the moment, i can only provide the things i wrote down when testing (will reproduce later)

**Test1**: /etc/resolv.conf is a static file
calling openfortivpn adds to this file
- search
- nameserver 

entries as expected (a lot of search entries coming from the company, but only2 nameserver items, so i am still in the limit of 3 nameserver entries and my local router is one of them)
Result: works as expected

**Test2**: /etc/resolv.conf is a symlink to /run/systemd/resolve/stub-resolv.conf
The default contents of /etc/resolv.conf are

    nameserver 127.0.0.53
    options edns0 trust-ad
    search local

Starting openfortivpn, the same search and nameserver entries are added to the (now symlinked) /etc/resolv.conf file.
But, this does not seem to be valid anymore for systemd-resolved to pick up.
When checking with

```
systemd-resolve --status
    Global
        Protocols: LLMNR=resolve -mDNS -DNSOverTLS DNSSEC=no/unsupported
    resolv.conf mode: stub                                                 

    Link 2 (enp0s31f6)
        Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6                                   
            Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
    Current DNS Server: 192.168.3.1                                                 
           DNS Servers: 192.168.3.1                                                 
            DNS Domain: local ~.                                                    

    Link 3 (tun1)
    Current Scopes: none                                                        
        Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

you can see that Link3 (tun1) does not have any information about nameservers or search-info (to complete non-fqdn domains with)
Result:
Browser or ssh cannot resolve DNS any more. But, going to the sites/servers by IP is possible, meaning the tunnel is running successfully.

I added 
```
sudo systemd-resolve --interface ppp0 --set-dns 10.62.32.11 --set-domain company.net
```
to test for one domain and this was working ok for browser and ssh.
(i'm not sure what the proper syntax is to add multiple domains (aka search entries) or multiple nameservers (comma separated list? multiple calls?.... did not find any docs for this and did not test any further)


Does this help?

**Comment by DimitriPapadopoulos** [comment] 2021-01-06 12:58
Test 1 is expected to work.

Test 2 is not supported, _systemd_ will not take into account or even overwrite any changes by _openfortivpn_.

**Comment by slartibart70** [comment] 2021-01-06 13:03
well, yes... that was the reason for opening this bugticket initially...

Anything we can do right now for a workaround (besides manually  hacking in lines like 'systemd-resolved....' for any search entry and namesever?
Or is the preferred solution (for now) simply to make /etc/resolv.conf a static file (not symlinked to the stub) and be happy again until openforti is reworked?

**Comment by DimitriPapadopoulos** [comment] 2021-01-06 13:04
On Fedora 33, I suggest using [NewtorkManager-fortivpnssl](https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn). It does call _openfortivpn_ to create the tunnel but lets _NetworkManager_ handle routing/DNS, which in turn should call _systemd_.

**Comment by slartibart70** [comment] 2021-01-06 13:06
i see... ok, let's try this. I'll keep you updated :-)

**Comment by slartibart70** [comment] 2021-01-09 23:35
Hi,
i made some tests with plasma-nm-fortisslvpn and NetworkManager-fortisslvpn installed.
First impressions... not working as it should

What works:
```
Link 5 (ppp0)
    Current Scopes: DNS LLMNR/IPv4                                              
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 10.62.32.11                                                 
       DNS Servers: 10.62.32.11 10.62.32.12  
```
The nameservers are setup correctly.

The complete search path (which is pasted into the /etc/resolc.conf - stub/symlink (obviously without affecting systemd-resolvd) is not taken into account by networkmanager.
So i copied and pasted the search-line manually into the NM-forti ipv4/search domains form
After this, some name resolution (with short names) are resolved properly ex. vm1234 gets an answer from dig being expanded to vm1234.company.net

But: chrome browser still has problems opening company-websites which seem to make use of redirects (assumption! there is a central identity provider in place which intercepts the request to internal websites for login and redirects afterwards to the target site)

And:
se-linux is complaining about missing dac-override capability and being not allowed to getattr/read/open my ~/.ssh/certificates file for the ca-certificates.
A remedy for this was to set selinux to 'permissive' (testing only, i did not want to create rules yet)

Compared to using the static file (etc/resolv.conf), well, the NM approach is not working successfully and still seems to have problems interacting with the forti-server info and the systemd-resolvd
(the search info is pushed by the forti-server, maybe other things as well)

My conclusion: use the static /etc/resolv.conf approach for now, start openfortivpn manually on commandline (as i did already in fedora32) and all is working as expected

Any help on this?

**Comment by DimitriPapadopoulos** [comment] 2021-01-11 09:13
I won't really have time to help with _NetworkManager-fortivpnssl_. Yet I believe it's the best way to handle machines based on _NetworkManager_. But then _openfortivpn_ does not handle split DNS, which means _NetworkManager-fortivpnssl_ cannot handle it either for now - the split-DNS parameters are not passed by _openfortivpn_ to _NetworkManager-fortivpnssl_. That I can try to fix. It would help if I could see the (sanitized) output of `openfortivpn -v -v`, especially the parameters sent by the FortiGate in XML format.

Not sure about the difference between `dig` and _Google Chrome_. Anything in the system logs or in the [_Google Chrome_ logs](https://support.google.com/chrome/a/answer/6271282)?

I don't know about SELinux, it's always a pain to get things to work. You should probably open a bug report against _Fedora_, based on the instructions found in the system log file.

**Comment by slartibart70** [comment] 2021-01-11 11:18
I have put the fortivpn log here (sanitized, hopefully :-)
https://cust-owncloud.k-net.fr/s/7EWWrjqjK9NL4Sq

selinux: i could define rules myself, seems reasonable because the service needs access to my local (home-dir) files/certificates. dac-override could be bugworthy?

**Comment by DimitriPapadopoulos** [comment] 2021-01-11 13:23
This a rather complex split-tunnel configuration, with many entries, but I don't see why it shouldn't work:
```
<ipv4>
    <dns domain='city.ads.xxxxx.me;ads.xxxxx.me;eil.xxxxx.me;xxxxx.me;rzcity.ads.xxxxx.me;brandxxx.ads.xxxxx.me;xxnyfs.ads.xxxxx.me;    -xxxxxxxxx.com;dc.company.local;company-aut.xxxx.biz;res.xxnyxxx.travel;xxnyxxx.travel;xxx.emea.local;arce.xxxxx.me;xxnytm.local' />
    <dns ip='10.62.32.11' />
    <dns ip='10.62.32.12' />
    <assigned-addr ipv4='10.147.42.246' />
    <split-tunnel-info>
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.0' mask='255.255.254.0' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.0' mask='255.255.255.0' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='10.0.0.0' mask='255.0.0.0' />
        <addr ip='xxx.0.0.0' mask='254.0.0.0' />
        <addr ip='192.168.0.0' mask='255.255.0.0' />
        <addr ip='172.16.0.0' mask='255.240.0.0' />
        <addr ip='xxx.xxx.xxx.0' mask='255.255.255.0' />
        <addr ip='xxx.xxx.xxx.0' mask='255.255.255.0' />
        <addr ip='xxx.xxx.xxx.0' mask='255.255.255.0' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='xxx.xxx.xxx.xxx' mask='255.255.255.255' />
        <addr ip='10.147.0.0' mask='255.255.252.0' />
        <addr ip='10.147.32.0' mask='255.255.240.0' />
        <addr ip='10.147.128.0' mask='255.255.192.0' />
    </split-tunnel-info>
</ipv4>
```
No split-DNS here, the DNS part looks pretty simple, just the two DNS servers `10.62.32.11` and `10.62.32.12` taking over. This is a very common DNS configuration. We do have this split-tunnel complex configuration though, so it might be a routing issue. Do the above complex routing instructions appear in the system IPv4 routing configuration after starting _openfortivpn_? I want to make sure this is not a routing issue.

Ah, I think I've got it, you have way too many search domains:
[resolv.conf limited to six domains with a total of 256 characters](https://unix.stackexchange.com/questions/245849/resolv-conf-limited-to-six-domains-with-a-total-of-256-characters/245888#245888)
Ir looks like `/etc/resolv.conf` cannot handle the very complex DNS configuration at your place.

**Comment by DimitriPapadopoulos** [comment] 2021-01-11 13:34
You could verify the above by trying to resolve a name in some of the first 6 domains and then in some of the other domains.

**Comment by slartibart70** [comment] 2021-01-11 13:34
Thanks for the analysis.
Yes, there are a lot of search domains (not my fault, btw :-) . When you talk of "/etc/resolv.conf cannot handle this"... did you mean the static file or the symlinked one?
With the static file (my workaround) all is working as expected i don't see a limitation in search behaviour?
And when putting all the search data into the network-manager forti-form while using the symlinked(stub) resolv.conf maybe here we get a limitation?

**Comment by DimitriPapadopoulos** [comment] 2021-01-11 13:44
I don't know. It looks like the limitation has been somehow removed in recent versions of RedHat or glibc 2.26:
https://access.redhat.com/solutions/58028
Unfortunately it looks individual pieces of software may still fail, depending on the way they handle DNS queries.

**Comment by DimitriPapadopoulos** [comment] 2021-01-11 13:45
So the limitation is not with the `/etc/resolv.conf` file itself (of course) but with the different pieces of software that read this file.

**Comment by jchmielniak** [comment] 2021-01-21 13:26
Hi,
i can confirm the same problem with F33.
I use split dns and can provide logging if it helps.

Log for XML Connection:
<?xml version='1.0' encoding='utf-8'?>
<sslvpn-tunnel ver='2' dtls='1' patch='1'>
  <dtls-config heartbeat-interval='10' heartbeat-fail-count='10' heartbeat-idle-timeout='10' client-hello-timeout='10'/>
  <tunnel-method value='ppp'/>
  <tunnel-method value='tun'/>
  <fos platform='FG1K5D' major='6' minor='02' patch='2' build='1010' branch='1010'/>
  <auth-ses check-src-ip='1' tun-connect-without-reauth='0' tun-user-ses-timeout='30'/>
  <client-config save-password='on' keep-alive='on' auto-connect='off'/>
  <ipv4>
    <split-dns domains='hmmrz.lan,hmm.lan,zhp.lan' dnsserver1='10.10.4.205' dnsserver2='10.10.4.202'/>
    <assigned-addr ipv4='10.10.220.1'/>
    <split-tunnel-info>
      <addr ip='192.168.0.0' mask='255.255.0.0'/>
      <addr ip='10.10.0.0' mask='255.255.0.0'/>
      <addr ip='10.9.2.0' mask='255.255.255.0'/>
    </split-tunnel-info>
  </ipv4>
  <idle-timeout val='3600'/>
  <auth-timeout val='28800'/>
</sslvpn-tunnel>

I have to run manually resolvectl to set dns and domain for ppp0. Log was made with openfortivpn, but I use NetworkManager with Automatic DNS and 'use this connection for ressources on this network'

Jacek

**Comment by marco-santamaria** [comment] 2021-02-04 15:02
Same problem here with F33 and openfortivpn 1.14.1

**Comment by DimitriPapadopoulos** [comment] 2021-02-04 15:40
* Unfortunately _openfortivpn_ requires substantial changes to fully adapt to the most recent distributions that rely on systemd-resolved [such as Fedora 33](https://fedoramagazine.org/systemd-resolved-introduction-to-split-dns/). By "substantial", I mean beyond my current capacity to contribute.
* Yet [_NetworkManager-fortivpnssl_](https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn) is supposed to work. I suggest you use it instead of directly running _openfortivpn_ on Fedora 33. If _NetworkManager-fortivpnssl_ does not work for you, please open a ticket against _NetworkManager-fortivpnssl_.
* We're still interested in getting reports of course; it will help qualify the problem and improve _openfortivpn_ whenever someone is able to contribute. For pure DNS issues, the following would help :
  1. Show the contents of `/etc/resolv.conf` before/after the VPN connection.
  2. Give an example of the DNS issues you're experiencing, such as the output of the `systemd-resolve my.server` command. Also show the output of more traditional commands such as `nslookup my.server`.
  3. Run `openfortivpn -v -v` and paste at least the XML configuration sent by the FortiGate.
  4. Test different options related to DNS, typically `--use-resolvconf=0` vs. `--use-resolvconf=1`.

**Comment by marco-santamaria** [comment] 2021-02-08 14:16
The issue I have is only DNS related, as the tunnel is up and running and I can reach the server using the IP address.

i. My `/etc/resolv.conf` looks like this before the VPN connection

```
nameserver 127.0.0.53
options edns0 trust-ad
```

After the connection there are two additional IPs at the top of the file

ii. The output of `resolvectl status` looks something like this before the VPN connection

```
Global
       Protocols: LLMNR=resolve -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub                                                 

Link 2 (enp1s0)
Current Scopes: none                                                        
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (wlp0s20f3)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6                                   
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 8.8.8.8                                                     
       DNS Servers: 8.8.8.8                                                     
        DNS Domain: ~.                                                          

Link 4 (virbr0)
Current Scopes: none                                                        
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 5 (virbr0-nic)
Current Scopes: none                                                        
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

After the VPN connection the following item is added

```
Link 7 (ppp0)
Current Scopes: LLMNR/IPv4                                                  
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

iii . The output of `systemd-resolve` says always  `resolve call failed: 'xxxxxx.xxxx.xx' not found`, but  `nslookup` is resolving the domain name correctly.

iv. The only XML code that I can spot in the openfortivpn verbose output looks something like the following

```
<?xml version='1.0' encoding='utf-8'?><sslvpn-tunnel ver='2' dtls='1' patch='1'><dtls-config heartbeat-interval='10' heartbeat-fail-count='10' heartbeat-idle-timeout='10' client-hello-timeout='10' /><tunnel-method value='ppp' /><tunnel-method value='tun' /><fos platform='FG1K2D' major='6' minor='00' patch='11' build='0387' branch='0387' /><client-config save-password='off' keep-alive='off' auto-connect='off' /><ipv4><dns ip='x.x.x.x' /><dns ip='y.y.y.y' /><assigned-addr ipv4='z.z.z.z' /><split-tunnel-info><addr ip='w.w.w.w' mask='255.255.255.255' /> ...</split-tunnel-info></ipv4><idle-timeout val='3600' /><auth-timeout val='28800' /></sslvpn-tunnel>
```

where the two `dns ip` items contain the same IPs that have been added in `/etc/resolv.conf`

v. In my system the option `use-resolvconf` is not available, therefore I cannot test it.

Cheers

**Comment by DimitriPapadopoulos** [comment] 2021-02-08 18:44
i. File **`/etc/resolv.conf`** has been updated as expected. That's not ideal, but that's how it is for now.

ii. The PPP tunnel has been added. Unfortunately we cannot associate the new DNS servers to the tunnel, for lack of `systemd-resolved` support.

iii. That's to be expected: `systemd-resolve` queries `systemd-resolved` which does not take into account the changes in /etc/resolv.conf`., while `nslookup` uses the legacy DNS mechanism that does take into account `/etc/resolv.conf`. It all depends the mechanism used by your software.

iv. yes, you do have the DNS server addresses here `<dns ip='x.x.x.x' /><dns ip='y.y.y.y' />`. It makes sense since `/etc/resolv.conf` has been updated.

v. Ah right, that option has been disabled on Fedora because it doesn't work well - or rather used not to work on Fedora 32 but might work on Fedora 33. You may want to compile _openfortivpn_ and check if it works better with `--use-resolvconf`. If it works, we'll modify the Fedora 33 packages.

I understand `nslookup` does work in your case. Which piece of software doesn't work?

**Comment by marco-santamaria** [comment] 2021-02-09 14:20
> v. Ah right, that option has been disabled on Fedora because it doesn't work well - or rather used not to work on Fedora 32 but might work on Fedora 33. You may want to compile _openfortivpn_ and check if it works better with `--use-resolvconf`. If it works, we'll modify the Fedora 33 packages.

I'll try and I'll report here the result

> I understand `nslookup` does work in your case. Which piece of software doesn't work?

ssh and git are not working. Currently I am adding the IPs in `/etc/hosts` to make them work, as _NetworkManager-fortivpnssl_ does not support  2FA via SMS [(check here)](https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/merge_requests/19)

**Comment by emelenas** [comment] 2021-02-14 18:06
I ran into the same issue, also on a Fedora 33. I have compiled openfortivpn and  the option `--use-resolvconf` works as expected, setting the DNS servers and domain search, for me at least.

NetworkManager-fortisslvpn does not read the https response, what it does is use the info sent by pppd. See https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/issues/36 and https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/issues/33

**Comment by DimitriPapadopoulos** [comment] 2021-02-15 10:05
@emelenas I see, the short term solution for fedora is to reenable `--use-resolvconf` in fedora packages, starting with Fedora 33.

The long term solution remains to:
* fix _NetworkManager-fortisslvpn_,
* add Network-Manager and _systemd-resolved_ support.

**Comment by priiduneemre** [comment] 2022-02-15 05:57
> @emelenas I see, the short term solution for fedora is to reenable `--use-resolvconf` in fedora packages, starting with Fedora 33.
> 
> The long term solution remains to:
> 
>     * fix _NetworkManager-fortisslvpn_,
> 
>     * add Network-Manager and _systemd-resolved_ support.

Could the `--use-resolvconf` option be disabled again for packages built for Fedora 35? Everything seems to work with the `1.17.0.fc34` package, but says _no such option_ when uising `1.17.0.fc35`. Installed the F34 one by force to get around this issue.

**Comment by DimitriPapadopoulos** [comment] 2022-02-15 06:16
Why disable `--use-resolvconf`?

**Comment by priiduneemre** [comment] 2022-02-15 06:45
Sorry for the ambiguous wording. I was asking whether it HAS BEEN disabled (by accident? on purpose?).

The point was that the F35 package for `1.17.0-2` doesn't recognize the `--use-resolveconf` option anymore, while the one for F34 still does. Thus, the workaround is intact for F34, but not for F35 (as far as I can tell).

**Comment by DimitriPapadopoulos** [comment] 2022-02-18 16:47
What do you mean by "it does not appear to work"? What is the error message?

**Comment by akellar** [comment] 2022-02-18 16:57
I am running Fedora 35. NetworkManager-FortiSslVpn will establish the connection, route privately, but then not route publicly. We use split-tunneling and split-dns and I'm wondering if NetworkManager needs additional configuration. I'll try to investigate that as well unless you have any experience with it. 

At any rate, back to openfortivpn. This is what I see when using my configuration file:

`[user@computer-fedora ~]$ sudo openfortivpn -c /etc/openfortivpn/config
WARN:   Ignoring option "use-resolvconf".
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
Using interface ppp0
Connect: ppp0 <--> /dev/pts/0
INFO:   Got addresses: [x.x.x.x], ns [x.x.x.x], ns_suffix [domain.com]
INFO:   Negotiation complete.
INFO:   Got addresses: [x.x.x.x], ns [x.x.x.x], ns_suffix [domain.com]
INFO:   Negotiation complete.
INFO:   Negotiation complete.
local  IP address x.x.x.x
remote IP address x.x.x.x
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.
`
This is what I see if I try to call it inline:
`sudo openfortivpn --use-resolvconf -c /etc/openfortivpn/config
openfortivpn: unrecognized option '--use-resolvconf'
Usage: openfortivpn [<host>[:<port>]] [-u <user>] [-p <pass>]
                    [--otp=<otp>] [--otp-delay=<delay>] [--otp-prompt=<prompt>]
                    [--pinentry=<program>] [--realm=<realm>]
                    [--ifname=<ifname>] [--set-routes=<0|1>]
                    [--half-internet-routes=<0|1>] [--set-dns=<0|1>]
                    [--pppd-use-peerdns=<0|1>] [--pppd-log=<file>]
                    [--pppd-ifname=<string>] [--pppd-ipparam=<string>]
                    [--pppd-call=<name>] [--pppd-plugin=<file>]
                    [--ca-file=<file>]
                    [--user-cert=<file>] [--user-key=<file>]
                    [--use-syslog] [--trusted-cert=<digest>]
                    [--persistent=<interval>] [-c <file>] [-v|-q]
       openfortivpn --help
       openfortivpn --version
`

**Comment by priiduneemre** [comment] 2022-02-25 06:41
@akellar: Try installing `1.17.0-2.fc34` (i.e. the latest version of the same package for Fedora 34). See if `-use-resolvconf` works there.

**Comment by DimitriPapadopoulos** [comment] 2022-02-25 08:20
Indeed, `openfortivpn-1.17.0-2.fc34` had been released on 21 August 2021 and was supposed to have re-enabled resolvconf support.
https://src.fedoraproject.org/rpms/openfortivpn/c/e18bf25eec9db844634286252acd46d78266a6bf?branch=f34

**Comment by DimitriPapadopoulos** [comment] 2022-02-25 08:30
Unfortunately, it looks like the bug has not really been fixed. Please follow up in #957. This bug report was about Fedora 33 which is EOL'ed.

**Closed by DimitriPapadopoulos** 2022-02-25 08:30 UTC
Labels: duplicate
