### ISSUE TITLE
ERROR:  pppd: terminated by signal: Hangup: 1

### ISSUE THREAD

**Issue by Saratoga6** [adrienverge/openfortivpn#552] opened 2020-02-28 21:41 UTC
Hello ,  any insight to this error is appreciated.   instinct tells me  from the fortigate?

My Client:
ProductName: Mac OS X
ProductVersion: 10.15.3
BuildVersion: 19D76

ERROR:  pppd: terminated by signal: Hangup: 1

regards
-finn

---
% sudo openfortivpn vpn.mydomain.com:<some custom port> -u myemail.mydomain.com -v
DEBUG:  openfortivpn 1.11.0
DEBUG:  Loaded config file "/usr/local/Cellar/openfortivpn/1.11.0/etc/openfortivpn/config".
VPN account password: 
DEBUG:  Config host = "vpn.mydomain.com"
DEBUG:  Config realm = ""
DEBUG:  Config port = "<our custom port>"
DEBUG:  Config username = "myemail.mydomain.com"
DEBUG:  Resolving gateway host ip
DEBUG:  Establishing ssl connection
DEBUG:  server_addr: <VPN perimeter IP Fortigate500E>
DEBUG:  server_port: <some custom port>
DEBUG:  gateway_addr: <VPN perimeter IP Fortigate500E>
DEBUG:  gateway_port: <some custom port>
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4DEBUG:  Gateway certificate validation succeeded.
INFO:   Connected to gateway.
DEBUG:  Cookie: SVPNCOOKIE=<some Cookie>
INFO:   Authenticated.12sB
DEBUG:  Cookie: SVPNCOOKIE=<some Cookie>
DEBUG:  Error reading from SSL connection (Connection reset by peer).
DEBUG:  server_addr: <VPN perimeter IP Fortigate500E>
DEBUG:  server_port: <some custom port>
DEBUG:  gateway_addr: <VPN perimeter IP Fortigate500E>
DEBUG:  gateway_port: <some custom port>
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4DEBUG:  Gateway certificate validation succeeded.
INFO:   Remote gateway has allocated a VPN.
DEBUG:  server_addr: <VPN perimeter IP Fortigate500E>
DEBUG:  server_port: <some custom port>
DEBUG:  gateway_addr: <VPN perimeter IP Fortigate500E>
DEBUG:  gateway_port: <some custom port>
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4DEBUG:  Gateway certificate validation succeeded.
DEBUG:  Retrieving configuration
DEBUG:  found dns server <valid dns server> in xml configDEBUG:  found dns server <valid dns server> in xml configDEBUG:  Establishing the tunnel
DEBUG:  ppp_path: /usr/sbin/pppd
DEBUG:  Switch to tunneling mode
DEBUG:  Starting IO through the tunnel
DEBUG:  ssl_read thread
DEBUG:  pppd_read thread
DEBUG:  ssl_write thread
DEBUG:  if_config thread
DEBUG:  Error reading from SSL connection (Connection reset by peer).
INFO:   Cancelling threads...
DEBUG:  Got Address: 0.0.0.0
DEBUG:  pppd_write thread
DEBUG:  if_config: not ready yet...
DEBUG:  disconnecting
DEBUG:  Waiting for pppd to exit...
DEBUG:  waitpid: pppd terminated by signal 1
ERROR:  pppd: terminated by signal: Hangup: 1
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
DEBUG:  server_addr: <VPN perimeter IP Fortigate500E>
DEBUG:  server_port: <some custom port>
DEBUG:  gateway_addr: <VPN perimeter IP Fortigate500E>
DEBUG:  gateway_port: <some custom port>
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4DEBUG:  Gateway certificate validation succeeded.
INFO:   Logged out.

**Comment by DimitriPapadopoulos** [comment] 2020-02-28 22:05
Yes, at first site that's the FortiGate closing the connection:
```
DEBUG: Error reading from SSL connection (Connection reset by peer).
```

Does this happen immediately after launching the VPN? Hours later? Does _FortiCLient_ work any better?

**Comment by Saratoga6** [comment] 2020-02-29 00:50
Immediately  after launching VPN I receive.    Forticlient  works , yes.

**Comment by Saratoga6** [comment] 2020-02-29 01:18
Dimitri,  yes thanks ,we are good.

INFO:   Tunnel is up and running.


Thanks again for your help.

-finn

**Comment by DimitriPapadopoulos** [comment] 2020-02-29 08:56
@Saratoga6 Do you mean the problem is solved? For the record, would you be willing to share what the problem was, or at least whether you had to modify anything on the FortiGate device or in the _openforitvpn_ parameters?

**Comment by Saratoga6** [comment] 2020-02-29 17:38
yes solves. the issue had to do with the access point , according to
network eng- no details relayed to me. -finn

**Comment by DimitriPapadopoulos** [comment] 2020-03-02 07:42
@Saratoga6 Thank you for sharing this. Closing this issue.

**Closed by DimitriPapadopoulos** 2020-03-02 07:42 UTC

**Comment by Saratoga6** [comment] 2020-03-02 17:52
hi dimitri, would it be possible to update the HomeBrew install to latest
to resolve that issue with the  commenting out the config  file so it  does
not override the cmd line arguments?  We got a load of laptops we ready to
deploy  this solution, woudl a possible  alternative is to delete the
file?   thanks
-tom

**Comment by DimitriPapadopoulos** [comment] 2020-03-02 19:04
Oh, we are not responsible for packaging _openfortivpn_ for specific platforms. Yet I know 1.12.0 is under way on Homebrew:
Homebrew/homebrew-core/pull/50728

And yes, you can delete the template configuration file or change it into a valid configuration file by removing/commenting these lines:
```
username =
password =
```
and setting these lines to point to your VPN:
```
host =
port =
```
