### ISSUE TITLE
DNS not working under MacOS

### ISSUE THREAD

**Issue by beremour** [adrienverge/openfortivpn#987] opened 2022-06-01 20:15 UTC
I have openfortivpn 1.17.1 from "homebrew" ports. Openfortivpn cannot add internal domains to resolve and name servers under MacOS.

While debug looks good:
```
INFO:   Adding VPN nameservers...
DEBUG:  Attempting to modify /etc/resolv.conf directly.
DEBUG:  Adding "nameserver 10.1.1.2", to /etc/resolv.conf.
DEBUG:  Adding "nameserver 10.1.1.3", to /etc/resolv.conf.
DEBUG:  Adding "search domain1.local domain2.local", to /etc/resolv.conf.
INFO:   Tunnel is up and running.
```
noting happens then. MacOS tool "scutil --dns" dosen't show new domains to be served. And "ping hostname" doesn't resolve hostname.

Thank you

**Comment by DimitriPapadopoulos** [comment] 2022-06-02 07:33
Isn't this a duplicate of #534?

**Comment by beremour** [comment] 2022-06-02 11:27
Yes! The same.. Thank you! Hope there will be some solution.

**Comment by DimitriPapadopoulos** [comment] 2022-06-03 06:03
Follow up in #534.

**Closed by DimitriPapadopoulos** 2022-06-03 06:03 UTC
Labels: duplicate
