### ISSUE TITLE
Docker/kubernetes issue

### ISSUE THREAD

**Issue by EnriqueRiveiro** [adrienverge/openfortivpn#485] opened 2019-10-24 15:34 UTC
Hello,
I have been doing a series of tests to use the project with docker and use it as a kind of gateway with nginx in docker or kubernetes.
It seems that everything works correctly, I have access to the VPN but after 15 minutes I throw these messages and it falls.
I have based on this repository and I have used version v1.10.0 in my project
https://github.com/makinacorpus/docker-fortivpn
Thanks and best regards

```
INFO:   Cancelling threads...
INFO:   Setting ppp interface down.
INFO:   Restoring routes...
INFO:   Removing VPN nameservers...
Hangup (SIGHUP)
Modem hangup
Connect time 15.0 minutes.
Sent 0 bytes, received 0 bytes.
Connection terminated.
INFO:   pppd: The link was terminated by the modem hanging up.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.
ret: 0
Stop /etc/hosts refresh !
```

**Comment by DimitriPapadopoulos** [comment] 2019-10-24 16:34
This `Connect time 15.0 minutes` message is probably related to a 15 minutes time-out on the FortiGate appliance. Perhaps you just need to properly set up the FortiGate appliance.

Is this specific to Docker boxes?

**Comment by DimitriPapadopoulos** [comment] 2019-10-24 16:47
Just noticed the complicate setup with the [_glider_ forward proxy](https://github.com/nadoo/glider). Not sure I understand everything here, but chances are the time-out is related to _glider_ or the FortiGate appliance. If the time-out is enforced by the FortiGate appliance despite actual VPN traffic, then there's not much we can do about it, can we?

**Comment by EnriqueRiveiro** [comment] 2019-10-24 18:10
I will try tomorrow to contact the client and check if it is something of the FortiGate. If I find the solution, I'll post here the solution or the point where it is.
Thanks so much

**Comment by DimitriPapadopoulos** [comment] 2019-11-05 09:51
@EnriqueRiveiro Have you been able to look into this issue? Is the time-out related to _glider_ or the FortiGate appliance?

**Comment by EnriqueRiveiro** [comment] 2019-11-05 13:58
What's up, I'm sorry to report nothing. Well, the problem did not come from the device itself, since it is reset every 8 hours. But the problem of losing the connection I have been able to solve it by maintaining a connection with the vpn every X time, I only ping it

**Comment by mrbaseman** [comment] 2019-11-05 15:14
hmm... to me it sounds as if you run into the tcp timeout. We had discussion about this in the past, and I think we came to the conclusion that there is no keepalive mechanism implemented. However, generating some traffic (e.g. sending a few packets with ping every couple of minutes) is enough to prevent the connection from being closed. @DimitriPapadopoulos, should we perhaps add a note about this on the [wiki ](https://github.com/adrienverge/openfortivpn/wiki)?

**Comment by DimitriPapadopoulos** [comment] 2019-11-06 09:14
@mrbaseman Sure we probably need to document the TCP time-out. But I cannot recall where exactly this TCP time-out would be implemented - probably not the FortiGate appliance or even the client running _openfortivpn_. Can you help?

I'm asking because I seem to recall _openfortivpn_ would keep running without interruption on an idle Ubuntu 16.04 workstation at my place until it would hit the FortiGate appliance time-out (a dozen hours later). Perhaps the workstation generates just enough network traffic (NTP, system updates) to keep the TCP connection alive. However that would be surprising if the time-out is 15 minutes.

**Comment by DimitriPapadopoulos** [comment] 2019-11-06 10:23
@EnriqueRiveiro The 15 minutes time-out probably originates in the _glider_ forward proxy or some other network element used by VPN traffic. You may try to change the parameters of the proxy - or alternatively pinging as you do to artificially create network traffic and avoid the proxy closing the VPN connection.

**Comment by mrbaseman** [comment] 2019-11-07 10:38
@DimitriPapadopoulos exactly, a tcp timeout can be configured anywhere along the network path between the client and the Fortigate. I'm not sure if the settings of the [session-ttl](https://kb.fortinet.com/kb/documentLink.do?externalID=FD40914) affect the connections **to** the Fortigate as well or if they are a dedicated setting for connections **through** the fortigate. 

I have found an interesting article about [TCP keepalive](http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html) in the linux kernel. Maybe users who run into the trouble with their tcp connections should adjust those parameters such that the keepalive is triggered often enough for the network path of their vpn connection.

As an alterntative, a manual ping through the vpn tunnel, out of a cronjob would do more or less the same, but you would have to check the return value to make sure that at least one icmp packet gets through without being dropped somewhere.

**Comment by DimitriPapadopoulos** [comment] 2019-11-13 09:37
@EnriqueRiveiro Can we clmse this issue from your point of view? It does not seem to be related to _openfortivpn_ but to your network setup - unless you cannot reproduce the timeout with _FortiClient_.

**Comment by DimitriPapadopoulos** [comment] 2019-11-13 09:50
@mrbaseman We could document that in the wiki, yes.

However for that we would need to clarify whether [session-ttl](https://kb.fortinet.com/kb/documentLink.do?externalID=FD40914) affects the connections *to* the _FortiGate_ appliance or if it is a dedicated setting for connections *through* the _FortiGate_ appliance.

Also it looks like we need to make a distinction between timeouts involving:
- the VPN connection to the _FortiGate_ appliance itself,
- network traffic tunnelled through the VPN and possibly caused by network equipment before or after the VPN tunnel or even by the _FortiGate_ appliance itself (see the above [session-ttl](https://kb.fortinet.com/kb/documentLink.do?externalID=FD40914) setting).

**Comment by mrbaseman** [comment] 2019-11-20 22:51
in the first place the session-ttl setting affects connections _through_ the FortiGate, even depending on the IP protocol and (destination) port they use. However, there is also a default value which is taken when no port-specific rule applies. I'm not sure if that default value is directly applied to the connections to the FortiGate, too, but indirectly, if sessions through the channel are dropped after that timeout, the whole vpn tunnel becomes inactive after some time and it might run into the same problem that network equipment on the way from the client to the FortiGate may time out the connection.
I don't have a clear idea yet how to test the behavior, and especially how to run those tests without breaking other things that currently work in my environment.

**Comment by pgporada** [comment] 2020-01-29 18:24
I have a test fortigate device that hits the 15 minute timeout just like the OP. The forticlientsslvpn_cli has a keepalive flag and doesn't time me out. Could something similar be implemented in openfortivpn? Let me know if you need any information. There are long periods of time when I won't need to access anything on the fortigate network, but when I do and have to reauth it's a bit annoying.

**Comment by DimitriPapadopoulos** [comment] 2020-03-12 09:10
@pgporada Just noticed your comment from 29 January. You might want to open a separate ticket as this one is closed. Where is the _FortiClient_ keep alive flag documented? A screen capture of _FortiClient_ showing how to set this keep alive flag perhaps?

**Closed** 2022-07-19 08:02 UTC
Labels: question
