### ISSUE TITLE
misleading warning when stdout is not a tty

### ISSUE THREAD

**Issue by symphorien** [adrienverge/openfortivpn#985] opened 2022-04-26 10:34 UTC
Logs of a successful connection:
```
WARN:   Could not load configuration file "/var/lib/NetworkManager-fortisslvpn/9d7dac1d-12e7-4b62-a422-915b6f9ba507.config" (Inappropriate ioctl for device).
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
```

As you can see, there is a warning that the configuration was not read and yet the connection succeeds, meaning that the password was read from the configuration file!

With strace one can see that the configuration file is correctly loaded and that the error message (inappropriate ioctl for device) is a red herring:
```
[pid 1915148] brk(NULL)                 = 0x4d7000
[pid 1915148] brk(0x4f8000)             = 0x4f8000
[pid 1915148] prctl(PR_CAPBSET_READ, CAP_MAC_OVERRIDE) = 0
[pid 1915148] prctl(PR_CAPBSET_READ, 0x30 /* CAP_??? */) = -1 EINVAL (Invalid argument)
[pid 1915148] prctl(PR_CAPBSET_READ, CAP_CHECKPOINT_RESTORE) = 0
[pid 1915148] prctl(PR_CAPBSET_READ, 0x2c /* CAP_??? */) = -1 EINVAL (Invalid argument)
[pid 1915148] prctl(PR_CAPBSET_READ, 0x2a /* CAP_??? */) = -1 EINVAL (Invalid argument)
[pid 1915148] prctl(PR_CAPBSET_READ, 0x29 /* CAP_??? */) = -1 EINVAL (Invalid argument)
[pid 1915148] ioctl(1, TCGETS, 0x7ffd29ed6410) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 1915148] openat(AT_FDCWD, "/var/lib/NetworkManager-fortisslvpn/9d7dac1d-12e7-4b62-a422-915b6f9ba507.config", O_RDONLY) = 3
[pid 1915148] newfstatat(3, "", {st_mode=S_IFREG|0600, st_size=40, ...}, AT_EMPTY_PATH) = 0
[pid 1915148] newfstatat(3, "", {st_mode=S_IFREG|0600, st_size=40, ...}, AT_EMPTY_PATH) = 0
[pid 1915148] read(3, "username = username\npassword = 12345678\n", 4096) = 40
[pid 1915148] read(3, "", 4096)         = 0
[pid 1915148] close(3)                  = 0
[pid 1915148] newfstatat(1, "", {st_mode=S_IFSOCK|0777, st_size=0, ...}, AT_EMPTY_PATH) = 0
[pid 1915148] write(1, "WARN:   Could not load configuration file \"/var/lib/NetworkManager-fortisslvpn/9d7dac1d-12e7-4b62-a422-915b6f9ba507.config\" (Inappropriate ioctl for device).\n", 158) = 158
```
the only system call that fails is an ioctl on stdout that happens *before* the config file is even opened.

In my specific case, the connection would not open because of a dns issue, but I spent a lot of time thinking it was a sandboxing issue where the configuration file would not be readable or something like this.

NixOS 22.05, networkmanager-1.36.4, NetworkManager-fortisslvpn-gnome-1.4.0, openfortivpn-1.17.2

**Comment by DimitriPapadopoulos** [comment] 2022-04-26 10:38
Duplicate of #976.

**Closed by DimitriPapadopoulos** 2022-04-26 10:38 UTC
Labels: duplicate
