### ISSUE TITLE
systemd.resolved resets /etc/resolv.conf and connection is lost.

### ISSUE THREAD

**Issue by theinvisible** [adrienverge/openfortivpn#332] opened 2018-06-09 18:38 UTC
Following bug was posted on OpenFortiGUI: https://github.com/theinvisible/openfortigui/issues/41

Maybe this bug was already fixed with this commit? https://github.com/adrienverge/openfortivpn/commit/6772c53c6f18ba73b55aca7aed4f10f8d4cecd65

Have you maybe tested already with Ubuntu 18.04, thanks.

-------------------

On systems using systemd.resolved the connection breaks when systemd resets resolv.conf to default. It happens after a few miinutes.

Replacing systemd.resolved with another resolver the problem is solved, but it would be good if OpenFortiGui could work with systemd.reolved since more and more systems are using it (Ubuntu 18.04 is one).

**Comment by DimitriPapadopoulos** [comment] 2018-06-10 09:29
Note that #330 somehow breaks compatibility, in the sense my current settings with _openfortivpn_ 1.7.0:
`--set-dns=0`/`--no-dns`/`set-dns=0`
`pppd-use-peerdns=1`
will need to be changed to:
`--set-dns=1`/`set-dns=1`
`pppd-use-peerdns=1`

That's very unfortunate, but then the previous situation was a mess and I feel it cannot be fixed without breaking compatibility.

**Comment by mrbaseman** [comment] 2018-11-18 22:48
for the record, the [above mentioned](https://github.com/adrienverge/openfortivpn/issues/332#issuecomment-396034524) change of DNS handling went into the recently released version 1.8.0

**Comment by mrbaseman** [comment] 2018-12-14 22:30
and with 1.8.1 we are back to the previous behavior. I'm not sure what _openfortivpn_ can do to avoid this problem. In my understanding, systemd.resolved messes up `/etc/resolv.conf`. So the question would be how can it be taught that the modifications of `/etc/resolv.conf` are intended? 
With the behavior restored in 1.8.1 the `--no-dns` option tells _openfortivpn_ *not* to change `/etc/resolv.conf`.  However, with `pppd-use-peerdns=1` tells `pppd` to request the dns servers. It also maintains `/var/run/ppp/resolv.conf`. In additiion we need either a pppd-ip-up script (see our [wiki](https://github.com/adrienverge/openfortivpn/wiki)) or perhaps the systemd.resolved must be instructed to synchronize this file to `/etc`

**Comment by mrbaseman** [comment] 2018-12-18 22:57
In #419 I have suggested a more detailed documentation of the relevant options, both in the man page and in the `--help` output

**Comment by DimitriPapadopoulos** [comment] 2019-05-08 08:09
@theinvisible I think we can close this issue now that _openfortivpn_ 1.9.0 has been released. Do you agree?

**Comment by mrbaseman** [comment] 2019-06-14 14:07
I'd say we can close this now.

**Closed by mrbaseman** 2019-06-14 14:07 UTC

**Comment by uishon** [comment] 2020-04-27 20:47
Encountering the same issue of `systemd-resolved` with _openfortivpn 1.6_ on Ubuntu 18.04.,
Was hoping this will be resolved with _openfortivpn 1.12_ on Ubuntu 20.04 but it's not.
Tried with and without `--no-dns` and `pppd-use-peer-dns`.  `/etc/resolv.con` is updated correctly but after a couple of minutes it's reset.
Any idea?

**Comment by DimitriPapadopoulos** [comment] 2020-04-27 20:52
While I cannot reproduce that on my own Ubuntu 20.04 machine it does make sense.

However please open a new issue, this one is closed.

**Comment by uishon** [comment] 2020-04-27 21:20
Thanks. Just created https://github.com/adrienverge/openfortivpn/issues/674.
