### ISSUE TITLE
socket: Too many open files

### ISSUE THREAD

**Issue by dovi5988** [adrienverge/openfortivpn#462] opened 2019-08-20 01:17 UTC
Hi,

Not sure if this is a local computer issue or something the forticlient. Every so often we see this in the log over and over, the only thing that helps is to kill it and restart:
Aug 19 21:14:11 n.e.org openfortivpn[947]: ERROR:  socket: Too many open files
Aug 19 21:14:11 n.e.org openfortivpn[947]: INFO:   Could not log out.
Aug 19 21:15:10 n.e.org openfortivpn[947]: ERROR:  socket: Too many open files
Aug 19 21:15:10 n.e.org openfortivpn[947]: INFO:   Closed connection to gateway.
Aug 19 21:15:10 n.e.org openfortivpn[947]: ERROR:  socket: Too many open files
Aug 19 21:15:10 n.e.org openfortivpn[947]: INFO:   Could not log out.
Aug 19 21:16:09 n.e.org openfortivpn[947]: ERROR:  socket: Too many open files
Aug 19 21:16:09 n.e.org openfortivpn[947]: INFO:   Closed connection to gateway.
Aug 19 21:16:09 n.e.org openfortivpn[947]: ERROR:  socket: Too many open files
Aug 19 21:16:09 n.e.org openfortivpn[947]: INFO:   Could not log out.

**Comment by mrbaseman** [comment] 2019-08-20 08:31
I believe you are running out of file descriptors for the sockets (see [this discussion](https://stackoverflow.com/questions/880557/socket-accept-too-many-open-files)). I don't think openfortivpn is the root cause, but that there is something else consuming the file descriptors.

**Comment by dovi5988** [comment] 2019-08-25 17:12
@mrbaseman I thought so but two things told me it wasn't:
1) [root@noc2 ~]#  cat /proc/sys/fs/file-max
283453
[root@noc2 ~]# 
2) When I restart the service it clears up. If the descriptors were full how would restarting it help?

**Comment by mrbaseman** [comment] 2019-08-26 11:26
Hmm. restarting the service may clear up things indirectly, because it removes the ppp interface and so everything else which binds to this interface is affected somehow. 

I have re-written the proposed C++ code from that discussion in C and included it into openfortivpn in my [debug_fd branch](https://github.com/mrbaseman/openfortivpn/tree/debug_fd). When you hit the `ERROR: socket: Too many open files` (and you are running in debug mode with -v) a full list of file descriptors is dumped together with the error and so (quoting the original author of the C++ code)  you will quickly figure out where the file handle leak is.

**Comment by DimitriPapadopoulos** [comment] 2019-11-05 10:04
@dovi5988 I'm closing this issue but please feel free re-open if you still think this might be an _openfortivpn_ issue.

**Comment by goug71** [comment] 2021-06-02 12:17
Hi Dimitri,

I'm hitting the same issue with the following situation : 
- persistence is active.
- remote certificate has changed.
After a while (~4k attempts), openfortivpn consistently consumes every FD in its context. A quick check with lsof | grep -c openfortivpn confirms this.
A easy guess is that either persistence loop starts too early in the code and could be moved after the socket (or any other FD)  was created, or the untrusted-cert error handling could use some FD cleanup.

**Comment by goug71** [comment] 2021-06-02 12:45
> Hi Dimitri,
> 
> I'm hitting the same issue with the following situation :
> 
> * persistence is active.
> * remote certificate has changed.
>   After a while (~4k attempts), openfortivpn consistently consumes every FD in its context. A quick check with lsof | grep -c openfortivpn confirms this.
>   An easy guess is that either persistence loop starts too early in the code and could be moved after the socket (or any other FD)  was created, or the untrusted-cert error handling could use some FD cleanup.

Indeed, socket created [here](https://github.com/adrienverge/openfortivpn/blob/d4d0548907e7a6147f0064ad5627078826841422/src/tunnel.c#L592) is never freed as far as I can read code

**Comment by DimitriPapadopoulos** [comment] 2021-06-02 14:42
Ah, interesting. I'll have a look at it.

**Comment by DimitriPapadopoulos** [comment] 2021-06-03 08:40
@goug71 I am not certain handle is never freed. This happens in a complex part of the code, successive functions calls are unclear, see #239.  Can you share your findings? It would help if you could add some debug code when `tunnel->ssl_socket` is created and destroyed.

**Comment by DimitriPapadopoulos** [comment] 2021-06-03 10:16
That  said, there are issues in _ssl_connect_(). For example `tunnel->ssl_socket` is created but not freed if `tunnel->ssl_context` or `tunnel->ssl_handle` cannot be initialized. I can fix that, but I'm not certain it will help in your case.

**Comment by DimitriPapadopoulos** [comment] 2021-06-03 11:24
Does #901 help in your case?

**Comment by DimitriPapadopoulos** [comment] 2021-06-03 11:55
The patch doesn't work for me. Because the logic behind the lifetime of `tunnel->ssl_socket`, `tunnel->ssl_context` and `tunnel->ssl_handle` is undocumented and intricate, I cannot fix it. Please just don't use the `--persistent` option. I had always been against this feature for this very reason: it's very difficult to manage resources properly after the fact, and there are alternatives such as _systemd_.

**Comment by DimitriPapadopoulos** [comment] 2021-06-04 07:09
@goug71 Another attempt at fixing it. I have re-worked the #901 pull request to partially fix the resource allocation/release issue. This way _openfortivpn_ still works for me. Does the `--persistent` option work any better for you?

**Comment by goug71** [comment] 2021-06-04 08:17
I'm so lame I don't even find out how to checkout your branch... However test is very simple, just check whether lsof -c | egrep openfotivpn incresases after each failed ssl attempt  in persistent mode (pointing to any closed local port is fine). I can test it if you just direct me a bit with git

**Comment by DimitriPapadopoulos** [comment] 2021-06-04 10:02
Ah, if I there is such a simple way to reproduce the problem, that's excellent news. I'll give it a try.

**Comment by DimitriPapadopoulos** [comment] 2021-06-04 11:18
Can you provide the exact commands I have to run to reproduce the problem? I have tried this:
```
sudo /my/path/openfortivpn 127.0.0.1:444 -u foobar --persistent=1
```
I do not see anything suspicious with `lsof`. How do you run `lsof` exactly?

**Comment by goug71** [comment] 2021-06-04 16:56
"lsof | grep -c openfortivpn" or "lsof -p <openfortivpn_pid> | wc -l" should give the number of files (including sockets) open by the process. If this is increasing over persistent attempts, then issue still exists.

**Comment by DimitriPapadopoulos** [comment] 2021-06-04 17:05
Unfortunately, I cannot reproduce this issue with this command, with or without #901:
```
sudo /my/path/openfortivpn 127.0.0.1:444 -u foobar --persistent=1
```

Do I need to start a local HTTPS server in order to reproduce this issue, perhaps with an incorrect certificate? Are you able to reproduce this issue with the above command?

**Comment by DimitriPapadopoulos** [comment] 2021-06-04 17:08
I'm testing on an up-to-date Linux Ubuntu 20.04 LTS.

**Comment by goug71** [comment] 2021-06-04 18:03
here you are : 
$ sudo lsof  | egrep openf
openforti 78299                        root  cwd       DIR                0,0        97 1099522575739 <REMOVED>
openforti 78299                        root  rtd       DIR               0,79      1024       1343068 /
openforti 78299                        root  txt       REG               0,80     84048        593246 /usr/bin/openfortivpn
openforti 78299                        root  mem       REG             252,16                  593246 /usr/bin/openfortivpn (path dev=0,80)
openforti 78299                        root  mem       REG             252,16                  262294 /lib/x86_64-linux-gnu/libgpg-error.so.0.26.1 (path dev=0,80)                                                                                                                                                            
openforti 78299                        root  mem       REG             252,16                  262291 /lib/x86_64-linux-gnu/libgcrypt.so.20.2.4 (path dev=0,80)
openforti 78299                        root  mem       REG             252,16                  603903 /usr/lib/x86_64-linux-gnu/liblz4.so.1.8.3 (path dev=0,80)
openforti 78299                        root  mem       REG             252,16                  262459 /lib/x86_64-linux-gnu/liblzma.so.5.2.4 (path dev=0,80)
openforti 78299                        root  mem       REG             252,16                  262230 /lib/x86_64-linux-gnu/librt-2.28.so (path dev=0,80)
openforti 78299                        root  mem       REG             252,16                  262216 /lib/x86_64-linux-gnu/libdl-2.28.so (path dev=0,80)
openforti 78299                        root  mem       REG             252,16                  262214 /lib/x86_64-linux-gnu/libc-2.28.so (path dev=0,80)
openforti 78299                        root  mem       REG             252,16                  262228 /lib/x86_64-linux-gnu/libpthread-2.28.so (path dev=0,80)
openforti 78299                        root  mem       REG             252,16                  262232 /lib/x86_64-linux-gnu/libutil-2.28.so (path dev=0,80)
openforti 78299                        root  mem       REG             252,16                  262313 /lib/x86_64-linux-gnu/libsystemd.so.0.25.0 (path dev=0,80)                                                                                                                                                              
openforti 78299                        root  mem       REG             252,16                  530073 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (path dev=0,80)                                                                                                                                                              
openforti 78299                        root  mem       REG             252,16                  530151 /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (path dev=0,80)
openforti 78299                        root  mem       REG             252,16                  262210 /lib/x86_64-linux-gnu/ld-2.28.so (path dev=0,80)
openforti 78299                        root    0u      CHR             136,11       0t0            14 /dev/pts/11
openforti 78299                        root    1u      CHR             136,11       0t0            14 /dev/pts/11
openforti 78299                        root    2u      CHR             136,11       0t0            14 /dev/pts/11
openforti 78299                        root    3u     sock                0,9       0t0     207285088 protocol: TCP
openforti 78299                        root    4u     sock                0,9       0t0     207285087 protocol: UNIX
openforti 78299                        root    5u     sock                0,9       0t0     207285092 protocol: TCP
openforti 78299                        root    6u     sock                0,9       0t0     207285094 protocol: TCP
openforti 78299                        root    7u     sock                0,9       0t0     207285101 protocol: TCP
openforti 78299                        root    8u     sock                0,9       0t0     207285103 protocol: TCP
openforti 78299                        root    9u     sock                0,9       0t0     207287097 protocol: TCP
openforti 78299                        root   10u     sock                0,9       0t0     207288472 protocol: TCP
openforti 78299                        root   11u     sock                0,9       0t0     207288841 protocol: TCP
openforti 78299                        root   12u     sock                0,9       0t0     207288843 protocol: TCP
openforti 78299                        root   13u     sock                0,9       0t0     207296094 protocol: TCP
openforti 78299                        root   14u     sock                0,9       0t0     207296098 protocol: TCP
openforti 78299                        root   15u     sock                0,9       0t0     207296101 protocol: TCP
openforti 78299                        root   16u     sock                0,9       0t0     207296106 protocol: TCP
openforti 78299                        root   17u     sock                0,9       0t0     207296129 protocol: TCP
openforti 78299                        root   18u     sock                0,9       0t0     207296135 protocol: TCP
openforti 78299                        root   19u     sock                0,9       0t0     207296138 protocol: TCP
openforti 78299                        root   20u     sock                0,9       0t0     207296140 protocol: TCP
openforti 78299                        root   21u     sock                0,9       0t0     207296143 protocol: TCP
openforti 78299                        root   22u     sock                0,9       0t0     207296148 protocol: TCP
openforti 78299                        root   23u     sock                0,9       0t0     207296154 protocol: TCP
openforti 78299                        root   24u     sock                0,9       0t0     207296156 protocol: TCP

**Comment by goug71** [comment] 2021-06-04 18:10
Well,  turns out the machine I took sample from has dual openfortivpn install : one from Debian Buster and one from gitHub souce. Debian version only triggers the bug... I'm really sorry for having you spending so much time on me skipping a very basic check.

**Comment by DimitriPapadopoulos** [comment] 2021-06-04 18:41
No worries. It did help clean up the code.
Puzzling issue for me, as I cannot recall any commit that would fix a socket leak.

**Closed** 2021-06-06 14:47 UTC

**Comment by mylix** [comment] 2022-08-29 13:29
@goug71 which version from Debian triggered the error? We are using the openfortivpn.x86_64 v1.17 from @epel repo for our centos7 installations and still running into it randomly.

**Comment by DimitriPapadopoulos** [comment] 2022-08-29 13:56
@mylix Are you running openfortivpn with `--persistent`? Are you able to reproduce this issue when building from source as well? If so, the suggestion in https://github.com/adrienverge/openfortivpn/issues/462#issuecomment-524823638 could help pinpoint the leak. Alternatively `strace` might help identify the leak too.

**Comment by goug71** [comment] 2022-08-29 15:39
@mylix, that would be the one shipped with Debian 10:buster : 1.8.1-1
Less probably the one with Debian 11:Bullseye : 1.15.0-1
Can't confirm, though. Sorry

**Comment by mylix** [comment] 2022-08-30 10:56
@DimitriPapadopoulos I think we might have solved the problem in our case. Our Fortigate was closing idle connections after 300s, and yes we are using openfortivpn with persistent flag. After every terminated connection, persistance reestablished it and that was burning down the sockets until there were too many open files.

**Comment by DimitriPapadopoulos** [comment] 2022-08-30 12:26
Yes, I have always been against the `--persistent` option, see #190. The application flow had been designed with a single connection in mind, and adding this option was not straightforward and an error-prone effort.

Especially in the case authentication is based on an immutable password, an external script might be better option. The case where `--persistent` is really useful is when authentication is not based on an immutable password, but re-connexion can use the existing session cookie instead of re-authentication.

I am unable to reproduce this issue with a simple setup such as https://github.com/adrienverge/openfortivpn/issues/462#issuecomment-854878999, as the `openfortivpn` process just hangs on a read call for way too long. I don't have the resources to set up something more complex. The log of `strace openfortivpn` might give a clue as to how the leak happens.

**Comment by DimitriPapadopoulos** [comment] 2022-08-30 12:35
I have tried:
```
sudo strace /volatile/local/opefortivpn/bin/openfortivpn 127.0.0.1:444 -u foobar -p foobar --persistent=1
```
The following loge covers a `--persistent=1` iteration:
```
[...]
nanosleep({tv_sec=1, tv_nsec=0}, 0x7ffdb37c1d90) = 0
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 3
getsockopt(3, SOL_SOCKET, SO_KEEPALIVE, [0], [4]) = 0
getsockopt(3, SOL_TCP, TCP_KEEPIDLE, [7200], [4]) = 0
getsockopt(3, SOL_TCP, TCP_KEEPINTVL, [75], [4]) = 0
getsockopt(3, SOL_TCP, TCP_KEEPCNT, [9], [4]) = 0
getsockopt(3, SOL_SOCKET, SO_SNDBUF, [16384], [4]) = 0
getsockopt(3, SOL_SOCKET, SO_RCVBUF, [131072], [4]) = 0
connect(3, {sa_family=AF_INET, sin_port=htons(444), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 ECONNREFUSED (Connection refused)
write(1, "\33[0;31mERROR:  connect: Connecti"..., 43ERROR:  connect: Connection refused
) = 43
write(1, "\33[0;0m", 6)                 = 6
close(3)                                = 0
write(1, "INFO:   Closed connection to gat"..., 38INFO:   Closed connection to gateway.
) = 38
write(1, "\33[0;0m", 6)                 = 6
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 3
getsockopt(3, SOL_SOCKET, SO_KEEPALIVE, [0], [4]) = 0
getsockopt(3, SOL_TCP, TCP_KEEPIDLE, [7200], [4]) = 0
getsockopt(3, SOL_TCP, TCP_KEEPINTVL, [75], [4]) = 0
getsockopt(3, SOL_TCP, TCP_KEEPCNT, [9], [4]) = 0
getsockopt(3, SOL_SOCKET, SO_SNDBUF, [16384], [4]) = 0
getsockopt(3, SOL_SOCKET, SO_RCVBUF, [131072], [4]) = 0
connect(3, {sa_family=AF_INET, sin_port=htons(444), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 ECONNREFUSED (Connection refused)
write(1, "\33[0;31mERROR:  connect: Connecti"..., 43ERROR:  connect: Connection refused
) = 43
write(1, "\33[0;0m", 6)                 = 6
close(3)                                = 0
write(1, "INFO:   Could not log out.\n", 27INFO:   Could not log out.
) = 27
write(1, "\33[0;0m", 6)                 = 6
nanosleep({tv_sec=1, tv_nsec=0}, 0x7ffdb37c1d90) = 0
[...]
```
As far as I can see we just have a pair of `socket(...) = 3` / `close(3)` calls per iteration, there doesn't seem to be a socket leak in this simple case.

**Comment by jarandas** [comment] 2022-11-07 08:15
Hello,
I am experiencing the same problem with versions from 1.14 to 1.17.
I have been able to verify that I only have two open sockets with the process constantly giving the too many open files error

```
# ps -ef |grep openfor|grep -v grep
root      1147     1  0 nov02 ?        00:04:02 /usr/bin/openfortivpn -c /etc/openfortivpn/cliente.conf

# lsof |grep 1147|wc -l
1044

# lsof |grep 1147|grep sock
openforti 1147 root 1u unix 0xffff8ea0f7c99200 0t0 22022 socket
openforti 1147 root 2u unix 0xffff8ea0f7c99200 0t0 22022 socket

Instead of TCP type:
# lsof |grep 1147|grep -c TCP
1021
```
I have tried to launch the strace at the moment I have the process error with the following result:
```

strace -d  -e trace=read,write,network,desc,signal,process -p 1147
strace: new tcb for pid 1147, active tcbs:1
strace: ptrace_setoptions = 0x51
strace: attach to pid 1147 (main) succeeded
strace: Process 1147 attached
strace: [wait(0x80057f) = 1147] WIFSTOPPED,sig=SIGTRAP,EVENT_STOP (128)
strace: next_event: queued pid 1147
strace: next_event: dequeued pid 1147
strace: pid 1147 has TCB_STARTUP, initializing it
strace: [wait(0x00857f) = 1147] WIFSTOPPED,sig=133
strace: next_event: queued pid 1147
strace: next_event: dequeued pid 1147
strace: [wait(0x00857f) = 1147] WIFSTOPPED,sig=133
strace: next_event: queued pid 1147
strace: next_event: dequeued pid 1147
strace: [wait(0x00857f) = 1147] WIFSTOPPED,sig=133
strace: next_event: queued pid 1147
strace: next_event: dequeued pid 1147
socket(AF_INET, SOCK_STREAM, IPPROTO_IPstrace: [wait(0x00857f) = 1147] WIFSTOPPED,sig=133
strace: next_event: queued pid 1147
strace: next_event: dequeued pid 1147
) = -1 EMFILE (Demasiados ficheros abiertos)
strace: [wait(0x00857f) = 1147] WIFSTOPPED,sig=133
strace: next_event: queued pid 1147
strace: next_event: dequeued pid 1147
write(1, "ERROR:  socket: Too many open fi"..., 36strace: [wait(0x00857f) = 1147] WIFSTOPPED,sig=133
strace: next_event: queued pid 1147
strace: next_event: dequeued pid 1147
) = 36
strace: [wait(0x00857f) = 1147] WIFSTOPPED,sig=133
strace: next_event: queued pid 1147
strace: next_event: dequeued pid 1147
write(1, "INFO:   Closed connection to gat"..., 38strace: [wait(0x00857f) = 1147] WIFSTOPPED,sig=133
strace: next_event: queued pid 1147
strace: next_event: dequeued pid 1147
) = 38
strace: [wait(0x00857f) = 1147] WIFSTOPPED,sig=133
strace: next_event: queued pid 1147
strace: next_event: dequeued pid 1147
socket(AF_INET, SOCK_STREAM, IPPROTO_IPstrace: [wait(0x00857f) = 1147] WIFSTOPPED,sig=133
strace: next_event: queued pid 1147
strace: next_event: dequeued pid 1147
) = -1 EMFILE (Demasiados ficheros abiertos)
strace: [wait(0x00857f) = 1147] WIFSTOPPED,sig=133
strace: next_event: queued pid 1147
strace: next_event: dequeued pid 1147
write(1, "ERROR:  socket: Too many open fi"..., 36strace: [wait(0x00857f) = 1147] WIFSTOPPED,sig=133
strace: next_event: queued pid 1147
strace: next_event: dequeued pid 1147
) = 36
```
The values of the configuration file are:

```
# cat /etc/openfortivpn/client.conf
host = XXX.XXX.XXX.XXX
port = XXXX
username = XXXX
password = XXCCXXXCXXCCX
set-routes = 1
set-dns = 1
pppd-use-peerdns = 1
user-cert = /etc/openfortivpn/client.cert.pem
user-key = /etc/openfortivpn/client.key.pem
trusted-cert = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
persistent = 10
use-syslog
```
The problem has occurred when my FW cluster performed a second uncontrolled Failover in an update

Regards.

**Comment by DimitriPapadopoulos** [comment] 2022-11-07 20:45
@jarandas This confirms it is a socket problem, as already diagnosed before:
```
# lsof |grep 1147|grep -c TCP
1021
```
It would help to see the actual list of all the TCP sockets and other files associated to `openfortivpn`:
```
sudo lsof -p `pgrep openfortivpn`
```
Could you post the (redacted if needed) output on [GitHubGist](https://gist.github.com) or similar site?
https://gist.github.com/starred

Also, a **complete** (redacted if needed) `strace` log would help (i) count sockets opening and closing and (ii) identify which sockets that are not closed.
