### ISSUE TITLE
No /etc/resolv.conf entries made by openfortivpn on Opensuse Leap 42.3

### ISSUE THREAD

**Issue by mirceadr** [adrienverge/openfortivpn#349] opened 2018-07-10 11:04 UTC
I can ping LAN IPs, so VPN tunnel is ok, I can ping external IPs , so routing is fine.
Any ping on domain names fails . Browser also gets stuck, even Midnight Commander.
/etc/resolv.conf  remains unmodified.

**Comment by DimitriPapadopoulos** [comment] 2018-07-10 11:35
Which version of _openfortivpn_? How was _openfortivpn_ started? Which options? A log (option `-v`) would help.

**Comment by DimitriPapadopoulos** [comment] 2018-07-10 12:02
Also could you provide the output of `ls -l /etc/resolv.conf` before/after running _openfortivpn_ ?

**Comment by DimitriPapadopoulos** [comment] 2018-07-10 12:08
Searching the web, I have also found a few ancient issues with `/etc/resolv.conf` on older versions of _openSUSE_. Perhaps it's unrelated though. Just for the sake of completeness:
* [Fix DNS problem on openSUSE](https://flanaras.wordpress.com/2016/09/26/fix-dns-problem-on-opensuse/)
* [How to fix the DNS in OpenSuSE 13.1 ?](https://goinggnu.wordpress.com/2013/10/14/how-to-fix-the-dns-in-opensuse-13-1/)

**Comment by mirceadr** [comment] 2018-07-10 12:58
openfortivpn --version  1.7.1 ( rpm based ) 

###

host = 89.238.206.106
port = 10443
username = mircea.dragota
password = XXXXXX
trusted-cert = 87aaa219b54cc00c7765d257bcfc94d326cdb23f8fdf84edcda747fcedea3330 
#set-dns = 0
#pppd-use-peerdns = 0

I tried with set-dns = 1 and pppd-use-peerdns = 1. same results

I ll get back with the log

**Comment by mirceadr** [comment] 2018-07-10 13:03
DEBUG:  Loaded config file "/etc/openfortivpn/config".
DEBUG:  Config host = "89.238.206.XXX"
DEBUG:  Config realm = ""
DEBUG:  Config port = "104xx"
DEBUG:  Config username = "mircea.dragota"
DEBUG:  Config password = "********"
DEBUG:  server_addr: 89.238.206.XXX
DEBUG:  server_port: 104xx
DEBUG:  gateway_addr: 89.238.206.XXX
DEBUG:  gateway_port: 104xx
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Connected to gateway.
DEBUG:  Cookie: SVPNCOOKIE=WwTqD8pnaVM/W9wPGMyqWM88rMHfk1hKdSZJ/0x8/L9CncRjma1AUveMjG8FFircxUbESaX2l+txIi7/xWJw/UYB+RCMJ7gPPUJRBHD6eYyy1kEkhTiYhi6NEn
8Gxr8/57IM3e9HaHDI8pDM634+BS+MAjPjBfcgME8HeKPTNncArsILgqtJE4zBWfgjLRKZsGKUp73r07YOqXDRxVqnE/hv6l8zV5Mqp4B0Zk58xV0=
INFO:   Authenticated.
DEBUG:  Cookie: SVPNCOOKIE=WwTqD8pnaVM/W9wPGMyqWM88rMHfk1hKdSZJ/0x8/L9CncRjma1AUveMjG8FFircxUbESaX2l+txIi7/xWJw/UYB+RCMJ7gPPUJRBHD6eYyy1kEkhTiYhi6NEn
8Gxr8/57IM3e9HaHDI8pDM634+BS+MAjPjBfcgME8HeKPTNncArsILgqtJE4zBWfgjLRKZsGKUp73r07YOqXDRxVqnE/hv6l8zV5Mqp4B0Zk58xV0=
INFO:   Remote gateway has allocated a VPN.
DEBUG:  server_addr: 89.238.206.XXX
DEBUG:  server_port: 104xx
DEBUG:  gateway_addr: 89.238.206.XXX
DEBUG:  gateway_port: 104xx
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
DEBUG:  pppd_read thread
DEBUG:  if_config thread
DEBUG:  ssl_read thread
DEBUG:  ssl_write thread
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  pppd ---> gateway (16 bytes)
DEBUG:  pppd_write thread
DEBUG:  pppd ---> gateway (12 bytes)
DEBUG:  gateway ---> pppd (16 bytes)
DEBUG:  pppd ---> gateway (10 bytes)
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  gateway ---> pppd (10 bytes)
DEBUG:  pppd ---> gateway (17 bytes)
DEBUG:  pppd ---> gateway (30 bytes)
DEBUG:  pppd ---> gateway (12 bytes)
DEBUG:  gateway ---> pppd (25 bytes)
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  pppd ---> gateway (24 bytes)
DEBUG:  pppd ---> gateway (12 bytes)
DEBUG:  gateway ---> pppd (24 bytes)
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  pppd ---> gateway (24 bytes)
DEBUG:  pppd ---> gateway (12 bytes)
DEBUG:  gateway ---> pppd (24 bytes)
INFO:   Got addresses: [10.212.134.200], ns [192.168.1.12, 192.168.1.12]
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  pppd ---> gateway (12 bytes)
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  pppd ---> gateway (12 bytes)
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  pppd ---> gateway (12 bytes)
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  pppd ---> gateway (12 bytes)
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  pppd ---> gateway (12 bytes)
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  pppd ---> gateway (12 bytes)
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  pppd ---> gateway (12 bytes)
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  pppd ---> gateway (12 bytes)
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  pppd ---> gateway (12 bytes)
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  pppd ---> gateway (12 bytes)
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  pppd ---> gateway (12 bytes)
DEBUG:  gateway ---> pppd (12 bytes)

**Comment by mirceadr** [comment] 2018-07-10 13:09
Before running openfortivpn
-rw-r--r-- 1 root root 87 Jul 10 15:59 /etc/resolv.conf 

After running opefortivpn

-rw-r--r-- 1 root root 87 Jul 10 16:05 /etc/resolv.conf

I even tried to manually put nameserver 192.168.1.12 in /etc/resolv.conf before running openfortivpn but this entry was lost after tunneling up. Seems like openfortivpn modifies resolv.conf but not adding nameserver...

**Comment by mirceadr** [comment] 2018-07-10 13:14
It s odd, running openfortivpn in terminal

linux-jyn7:~ # openfortivpn
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
INFO:   Got addresses: [10.212.134.200], ns [192.168.1.12, 192.168.1.12]
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.

But no VPN nameserver is added in /etc/resolv.conf

**Comment by mirceadr** [comment] 2018-07-10 14:12
Log completed

INFO:   Setting new routes...
DEBUG:  ip route show to 0.0.0.0/0.0.0.0
DEBUG:  ip route show to 89.238.206.106/255.255.255.255
DEBUG:  Setting route to vpn server...
DEBUG:  ip route show to 89.238.206.106/255.255.255.255 via 192.168.0.1 dev wlan0
DEBUG:  ip route add to 89.238.206.106/255.255.255.255 via 192.168.0.1 dev wlan0
DEBUG:  Deleting the current default route...
DEBUG:  ip route del to 0.0.0.0/0.0.0.0 via 192.168.0.1 dev wlan0
DEBUG:  Setting new default route...
DEBUG:  ip route add to 0.0.0.0/0.0.0.0 dev ppp0
INFO:   Adding VPN nameservers...
**DEBUG:  Adding "nameserver 192.168.1.12" and "nameserver 192.168.1.12" to /etc/resolv.conf.**
INFO:   Tunnel is up and running.
DEBUG:  pppd ---> gateway (975 bytes)

**Comment by mirceadr** [comment] 2018-07-10 16:58
As far as I see, nemservers are inserted in /var/run/ppp_resolc.conf.ppp0

linux-jyn7:~ # cat /var/run/ppp_resolv.conf.ppp0 
nameserver 192.168.1.12
nameserver 192.168.1.12
linux-jyn7:~ # ls -l /var/run/ppp_resolv.conf.ppp0
-rw-r--r-- 1 root root 48 Jul 10 19:54 /var/run/ppp_resolv.conf.ppp0

Then, why there s still no DNS response?

**Comment by DimitriPapadopoulos** [comment] 2018-07-10 19:14
Three different sets of options can be used to set DNS in _openfortivpn_ 1.7.1 and lower:
* `set-dns = 1` / `pppd-use-peerdns = 0` : _openfortivpn_ attempts to add the DNS servers provided by the _FortiGate_ device, exclusively by modifying file `/etc/resolv.conf`. Note that modifying `/etc/resolv.conf` might not be the proper way to set the DNS servers in recent Linux distributions.
* `set-dns = 0` / `pppd-use-peerdns = 1` : _openfortivpn_ does not attempt to modify `/etc/resolv.conf`, instead it passes the DNS server to _pppd_ and lets _pppd_ do the right thing.
* `set-dns = 1` / `pppd-use-peerdns = 1` : This is the default and the combination of the two above options.

Note that **the semantics of these options will change** in the next version of _openfortivpn_.

My suggestions:
1. Since _Leap_ 42.3 is a recent distribution, chances are `/etc/resolv.conf` is not the proper place to set DNS servers, which means you should probably use `set-dns = 0`. Instead use `pppd-use-peerdns = 1` to have _pppd_ set the DNS servers, hopefully doing the right thing. In short I suggest using this set of options:
`set-dns = 0` / `pppd-use-peerdns = 1`
2. Additionally define a log file for _pppd_ using _openfortivpn_ option `pppd-log` and have a look at the log file. Anything useful in there?
3. Use command [`nmcli dev show | grep DNS`](https://unix.stackexchange.com/questions/28941/what-dns-servers-am-i-using#77633) to find the current DNS server(s) on your system, before and after running _openfortivpn_.

**Comment by mirceadr** [comment] 2018-07-10 19:15
my ifconfig and routing table below. ( VPN ON )

eth0      Link encap:Ethernet  HWaddr 28:D2:44:51:1B:7C  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1072 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1072 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:85472 (83.4 Kb)  TX bytes:85472 (83.4 Kb)

ppp0      Link encap:Point-to-Point Protocol  
          inet addr:10.212.134.200  P-t-P:192.0.2.1  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1354  Metric:1
          RX packets:106 errors:0 dropped:0 overruns:0 frame:0
          TX packets:138 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:3 
          RX bytes:1082 (1.0 Kb)  TX bytes:4539 (4.4 Kb)

wlan0     Link encap:Ethernet  HWaddr 48:51:B7:3A:DC:25  
          inet addr:192.168.0.108  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::4a51:b7ff:fe3a:dc25/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:57835 errors:0 dropped:0 overruns:0 frame:0
          TX packets:28769 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:59128685 (56.3 Mb)  TX bytes:6691542 (6.3 Mb)

Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         0.0.0.0         0.0.0.0         U         0 0          0 ppp0
89.238.206.106  192.168.0.1     255.255.255.255 UGH       0 0          0 wlan0
192.0.2.1       0.0.0.0         255.255.255.255 UH        0 0          0 ppp0
192.168.0.0     0.0.0.0         255.255.255.0   U         0 0          0 wlan0

**Comment by mirceadr** [comment] 2018-07-10 19:28
config set to set-dns = 0 and pppd-use-peerdns = 1.
nmcli dev show  before tunnel and after seems to be the same.

linux-jyn7:~ # nmcli dev show | grep DNS
IP4.DNS[1]:                             78.96.7.88
IP4.DNS[2]:                             95.77.94.88
linux-jyn7:~ # nmcli dev show | grep DNS
IP4.DNS[1]:                             78.96.7.88
IP4.DNS[2]:                             95.77.94.88
I ll check pppd logs

**Comment by mirceadr** [comment] 2018-07-10 19:33
pppd log

sent [IPCP ConfRej id=0x66 <addrs 89.238.206.106 10.212.134.200>]
rcvd [IPCP ConfReq id=0x67]
sent [IPCP ConfAck id=0x67]
local  IP address 10.212.134.200
remote IP address 192.0.2.1
primary   DNS address 192.168.1.12
secondary DNS address 192.168.1.12
Script /etc/ppp/ip-up started (pid 17404)
Script /etc/ppp/ip-up finished (pid 17404), status = 0x0

192.168.1.12 is valid, domain controller's DNS

**Comment by mirceadr** [comment] 2018-07-10 19:47
I managed to manuallly add  192.168.1.12 namserver by editing wlan connection properties in NetworkManager.
linux-jyn7:~ # cat /etc/resolv.conf
# Generated by NetworkManager
search home                                                                                                                                          
nameserver 78.96.7.88                                                                                                                                
nameserver 95.77.94.88                                                                                                                               
nameserver 192.168.1.12  

**Now, i get DNS response but it takes too long ( I guess, because it is the third DNS and takes a while untill lookup reaches it ) .**

Now I have a clue, so nameserver 192.168.1.12 is expected to be the first nameserver on /etc/resolv.conf but, somehow,  openfortivpn is not doing it right.

**Comment by DimitriPapadopoulos** [comment] 2018-07-10 19:55
If you're using `set-dns = 0` / `pppd-use-peerdns = 1` then it's not _openfortivpn_ but _pppd_ not doing it right.

**Comment by DimitriPapadopoulos** [comment] 2018-07-10 20:46
Unfortunately I'm not familiar with _pppd_ and I'm not 100% certain _pppd_ is the culprit, but asking in OpenSuse forums is definitely a good idea. Note that _openfortivpn_ passes option `usepeerdns` to _pppd_.

By the way, does the following work any better?
`set-dns = 1` / `pppd-use-peerdns = 0`
If so it could be that _openfortivpn_ does the right thing after all unlike _pppd_.

**Comment by mirceadr** [comment] 2018-07-10 21:19
I tried this settings set-dns = 1 / pppd-use-peerdns = 0 

INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
**INFO:   Got addresses: [10.212.134.200], ns [0.0.0.0, 0.0.0.0]**
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.

No better results.

**Comment by DimitriPapadopoulos** [comment] 2018-07-10 21:49
This is suspect:
**INFO: Got addresses: [10.212.134.200], ns [0.0.0.0, 0.0.0.0]**

It should be:
**INFO: Got addresses: [10.212.134.200], ns [192.168.1.12, 192.168.1.12]**

As far as I can recall this dhouldn't depend on options `set-dns` and `pppd-use-peerdns`.

**Comment by mirceadr** [comment] 2018-07-11 06:14
After all , I came with this workaround : I manually put `nameserver 192.168.1.12` into a modified version of resolv.conf and i saved it as /opt/resolv.conf.2  After tunneling up, manually #cp /opt/resolv.conf.2 /etc/resolv.conf  .

Now it s working fine.

When I close the tunnel,  I found the original state of /etc/resolv.conf ( with no nameserver 192.168.1.12).
That makes me wonder why closing the connection got VPN namserver deleted( as it should ) but starting connection doesn t add it ( as it also should have )

**Comment by qb-cea** [comment] 2018-11-27 15:03
Hello, I think I have the exact same issue.

I am running 5a0c37e339a30437f5b5624658693cd1e0652a3e (master / 1.8.0 + a few patches) on an up-to-date Centos 7.5.

I tried all combinations of `set-dns` / `pppd-use-peerdns`:

| set-dns | pppd-use-peerdns | log messages | `/var/run/ppp/resolv.conf` |
| --- | --- | --- | --- |
| true | true | ns [1.2.3.4, 1.2.3.5] | created/updated |
| true | false | ns [0.0.0.0, 0.0.0.0] <br> Adding VPN nameservers... | **not** created/updated |
| false | true | ns [1.2.3.4, 1.2.3.5] | **not** created/updated |
| false | false | ns [0.0.0.0, 0.0.0.0] | **not** created/updated |

No matter the combination, `/etc/resolv.conf` is never modified.

This actually makes sense. openfortivpn only tries to edit `/etc/resolv.conf` when `set-dns=1 && pppd-user-peerdns=0` (cf. [src/tunnel.c::on_ppp_if_up()](https://github.com/adrienverge/openfortivpn/blob/5a0c37e339a30437f5b5624658693cd1e0652a3e/src/tunnel.c#L101)) and in this case [src/ipv4.c::ipv4_add_nameservers_to_resolv_conf()](https://github.com/adrienverge/openfortivpn/blob/5a0c37e339a30437f5b5624658693cd1e0652a3e/src/ipv4.c#L976) bails early because `tunnel->ipv4.ns1_addr.s_addr == 0` (as shown in the logs: `ns [0.0.0.0, 0.0.0.0]`).

From what I read on this repository, you seem to assume pppd will modify `/etc/resolv.conf` so long as it is called with the `usepeerdns` option, but the [man page](https://linux.die.net/man/8/pppd) only states:

> **usepeerdns**
> Ask the peer for up to 2 DNS server addresses. The addresses supplied by the peer (if any) are passed to the /etc/ppp/ip-up script in the environment variables DNS1 and DNS2, and the environment variable USEPEERDNS will be set to 1. In addition, pppd will create an /var/run/ppp/resolv.conf file containing one or two nameserver lines with the address(es) supplied by the peer.

Now, I only discovered openfortivpn and pppd today, so I cannot say for sure, but it seems to me that pppd is not meant to edit `/etc/resolv.conf` itself.

Reverting f3830844090d9107112fb83dd93089da4961add1, and using `set-dns=1 && pppd-user-peerdns=1` (the default) solved the issue for me.

**Comment by mrbaseman** [comment] 2018-11-27 15:21
I assume /etc/resolv.conf is supposed to be a symbolic link pointing to `/var/run/...` but something has replaced it by a static file in `/etc`

**Comment by qb-cea** [comment] 2018-11-27 15:44
> I assume `/etc/resolv.conf` is supposed to be a symbolic link

Maybe... But I don't think this is it. [man resolv.conf](https://linux.die.net/man/5/resolv.conf) mentions nothing of the sort, and [man pppd](https://linux.die.net/man/8/pppd) says nothing about `/etc/resolv.conf` pointing to `/var/run/...`.

**Comment by mirceadr** [comment] 2018-11-27 19:22
Opensuse Leap 15 works fine with openfortivpn 1.7.0 , /etc/resolv.conf being 
modified by openfortivpn, nameservers  placed at the very beginning of this 
file.

**Comment by mrbaseman** [comment] 2018-11-28 10:13
@mirceadr version 1.7.0 doesn't yet have f383084 yet. That commit was introduced in release 1.8.0. 

@qb-cea with 1.8.0 the **set-dns** option is supposed to switch the update mechanism for nameserver entries on/off completely. So, with set-dns=0 it is expected behavior, that neither `/etc/resolv.conf` nor `/var/run/ppp/resolv.conf` is updated.
With set-dns=1 nameservers are supposed to be updated. **pppd-use-peerdns** is supposed to switch  between `pppd` and `openfortivpn` to update `/etc/resolv.conf`. For pppd-use-peerdns=0 `openfortivpn` will take care of this, and with pppd-use-peerdns=1 `pppd` is responsible for the update. `pppd` however passes it to the `/etc/ppp/ip-up` script. The latter is not part of `pppd` but it is either something the distributor adds to the `pppd` installation, or the end user is supposed to maintain - or the network-manager is supposed to pick up the settings for the ppp interface and update `/etc/resolv.conf`accordingly. (This is the default behavior, btw.)

With set-dns=1 and pppd-use-peerdns=0  `/etc/resolv.conf` should be updated by `openfortivpn` directly (unless another mechanism, like network-manager interferes and thinks to know better what to do). set-dns=1 is the default, so one can ommit this, and --pppd-no-peerdns would be the official command line option for this behavior, which is supposed to be a workaround for situations in which the mechanisms around `pppd` don't work as expected.

BTW. On my Ubuntu 16.04, with  [resolvconf](https://www.freebsd.org/cgi/man.cgi?query=resolvconf&sektion=8) installed `/etc/resolv.conf` is a symbolic link to `/run/resolvconf/resolv.conf`

**Comment by qb-cea** [comment] 2018-11-28 12:11
> with set-dns=0 it is expected behavior, that neither /etc/resolv.conf nor /var/run/ppp/resolv.conf is updated.

I agree, I shouldn't have included that part in my message, sorry.

---

> with pppd-use-peerdns=1 pppd is responsible for the update

Ok, I found a bit more references about that.
[ppp HOWTO](https://www.tldp.org/HOWTO/PPP-HOWTO/ip-up.html) has a section about `/etc/ppp/ip-up` that reads:

> [/etc/ppp/ip-up] allows you to automate any special routing commands that may be necessary and any other actions that you want to occur every time the PPP link is activated.

While updating `/etc/resolv.conf` is not explicitely mentioned, I suppose it falls under the latter category.

Moreover [ppp's documentation on archwiki](https://wiki.archlinux.org/index.php/Ppp#PPPoE) presents that updating as a _de facto_ standard:

> If usepeerdns option is used, pppd will create the /etc/ppp/resolv.conf file with obtained DNS addresses while establishing a connection. By default, the /etc/ppp/ip-up.d/00_dns hook script moves this file to /etc/resolv.conf, allowing the system to use these name servers. If this is undesirable (e.g. you are using a local caching DNS), edit the /etc/ppp/ip-up.d/00_dns.sh as you need.

---

> With set-dns=1 and pppd-use-peerdns=0 /etc/resolv.conf should be updated by openfortivpn directly

It certainly should, but it __does not__. I tried to explain why, and I think this is because `openfortivpn` relies on `pppd` to figure out the nameserver's ip and that requires passing it the `usepeerdns` option.

---

Last but not least, considering `pppd` may or may not update `/etc/resolv.conf` depending on the distribution and/or users knowing they should edit `/etc/ppp/ip-up`, shouldn't the default be `pppd-use-peerdns=0`? This would guarantee that `openfortivpn` works out of the box for everyone.

Alternatively, I don't know how standard the `/etc/ppp/ip-up.d` setup described on archwiki is. But if it is, openfortivpn could add its own program there.

**Comment by mrbaseman** [comment] 2018-11-28 14:08
I can reproduce the problem that you describe with `openfortivpn` 1.8.0 on Ubuntu. Here, a file `/run/resolvconf/interfaces/ppp0` is updated, but only if pppd-use-peerdns is active. The fallback which should let `openfortivpn` update `/etc/resolv.conf` independently doesn't work as expected.

**Comment by mrbaseman** [comment] 2018-11-28 15:18
Looking again at the [agenda](https://github.com/adrienverge/openfortivpn/pull/330#issue-193774115) presented in the above mentioned pull request, it seems that we have skipped the next steps by accident. The internal mechanism to update `/etc/resolv.conf` ***already*** is disabled de facto. The question is if we shall go ahead and remove that code and the pppd-no-peerdns option or if we shall try to repair it in the next release to provide a smoother transition.

**Comment by DimitriPapadopoulos** [comment] 2018-11-29 01:03
@mrbaseman I'm on the move, will be back next week.

**Comment by mrbaseman** [comment] 2018-12-03 10:45
It seems that several distributions assume that the end-user has to configure ppp ip-up scripts to update `/etc/resolv.conf`. Maybe we shouldn't get rid of the internal mechanism for the update, but just offer an option to switch it off (for instance for users who have configured their own pppd scripts, openresolv or other mechanisms that would interfere with the internal mechanism of openfortivpn).

**Comment by mrbaseman** [comment] 2018-12-05 12:37
As noticed [above](https://github.com/adrienverge/openfortivpn/issues/349#issuecomment-442459026), with f383084 it is not possible anymore to use _openfortivpn_'s internal mechanism to update `/etc/resolv.conf`, because it ***also*** needs to pass the `usepeerdns` option to `pppd` in order to receive this information from the vpn server. The more I think about it, I believe returning to the previous behavior is the best solution. I have tried to summarize the combinations of the options and the result:

New behavior without specific ip-up scripts for the ppp interface or _openresolv_ service:

| set-dns | pppd-use-peerdns | `/var/run/ppp/resolv.conf` | `/etc/resolv.conf` |
| --- | --- | --- | --- | 
| true | true |  created/updated | **not** updated (default case) |
| true | false |  not created/updated | not updated (**broken**) |
| false | true |  **not** created/updated | not updated |
| false | false |  not created/updated | not updated |

old behavior (without specific ip-up scripts for the ppp interface or _openresolv_):

| set-dns | pppd-use-peerdns | `/var/run/ppp/resolv.conf` | `/etc/resolv.conf` |
| --- | --- | --- | --- | 
| true | true |  created/updated | **updated** (default case) |
| true | false |  not created/updated | not updated (**expected but not very intuitive**) |
| false | true |  **created/updated** | not updated (intended for _openresolv_ or `ip-up` script) |
| false | false |  not created/updated | not updated |

With `ip-up` script or _openresolv_, the new default behavior is the required one, with the old behavior `set-dns=0` would be needed. 
Without `ip-up` script or _openresolv_, the old default behavior is the required one, whereas there is **no** combination that can update `/etc/resolv.conf` out of the box.

**Comment by mrbaseman** [comment] 2018-12-11 14:05
@DimitriPapadopoulos did you have a chance to look into this? I didn't want to decide on my own to revert it, but I would vote for that. From today's perspective, probably the behavior already was the best we could do. 
We have a better understanding of the mechanisms now (some months ago, at least to me, it wasn't clear that the internal mechanism also needs that `usepeerdns` is sent to request the dns entries, and that in many cases `/etc/resolv.conf` is **not** updated without an explicit configuration ilke a user-supplied `ip-up` script).

**Comment by hotpxl** [comment] 2018-12-12 04:38
Same problem here, using Arch Linux and version 1.8.0.
If `pppd-use-peerdns`, I can receive the correct DNS address (as shown in the log output), but it will not set `resolv.conf` (`if (tunnel->config->set_dns && !tunnel->config->pppd_use_peerdns)`)

If `pppd-use-peerdns=0`, then pppd is started without `peerdns` and as shown in the log output, no nameservers are returned by the server.

**Comment by DimitriPapadopoulos** [comment] 2018-12-12 08:56
@Martin I'll have a hard time looking into this before the holiday season. I need some quality time to address this I don't have right now. From what I have gathered so far, I agree with you we should revert first. Then we probably need to document/name the options better, it's not clear what they do.

**Comment by mrbaseman** [comment] 2018-12-14 22:16
We have restored the behavior of versions before 1.8.0 by reverting f383084 and released 1.8.1 but I believe the original issue was already something else not working as expected. Before 1.8.0 we thought that this was specific to OpenSUSE Leap but maybe we have to review the analysis at the beginning of this issue with the knowledge that we have now.

**Comment by DimitriPapadopoulos** [comment] 2018-12-18 15:20
@mirceadr Could you give _openfortivpn_ 1.8.1 a try?

**Comment by mirceadr** [comment] 2018-12-18 15:56
Sure, where could I  find a .rpm version for 1.8.1 ?
Opensuse developers still stick to 1.7.x for both  Leap and  Tumbleweed distos

https://software.opensuse.org/package/openfortivpn

**Comment by DimitriPapadopoulos** [comment] 2018-12-18 16:02
Ah, you'd have to compile _openfortivpn_ yourself if no RPM is available.

Since this might be specific to _openSUSE_ I would recommend opening a ticket on the [_openSUSE_ bug tracker](https://bugzilla.opensuse.org/). This might help with specific configuration issues around `/etc/resov.conf` and might push the maintener to upgrade to 1.8.1.

**Comment by hotpxl** [comment] 2018-12-18 20:12
1.8.1 works for me on Arch Linux now.

**Comment by DimitriPapadopoulos** [comment] 2019-04-19 16:59
@mirceadr New 1.9.0 RPMs should be available by now. Have you had a chance to test them? I would like to close this issue since it looks like version 1.8.1 does seem to fix this issue for @hotpxl.

**Comment by rmuehl** [comment] 2019-05-08 06:25
If you are using DHCP, just delete /etc/resolv.conf and reboot.

**Closed** 2019-05-08 08:01 UTC
