### ISSUE TITLE
Issues connecting from Mojave

### ISSUE THREAD

**Issue by madrover** [adrienverge/openfortivpn#470] opened 2019-09-16 13:19 UTC
Hi.
I am using version 1.10.0 from Macos Mojave and, even though the VPN seems to connect, I can not access any service exposed on the VPN and the VPN stops in 20-30 seconds approximately.

The command output is:

> WARN:   You should not pass the password on the command line. Type it interactively or use a config file instead.
WARN:   Bad port in config file: "0".
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
INFO:   No split VPN route
Mon Sep 16 15:10:50 2019 : publish_entry SCDSet() failed: Success!
Mon Sep 16 15:10:50 2019 : publish_entry SCDSet() failed: Success!
Mon Sep 16 15:10:50 2019 : Using interface ppp0
Mon Sep 16 15:10:50 2019 : Connect: ppp0 <--> /dev/ttys003
INFO:   Got addresses: [172.28.133.28], ns [10.215.137.194, 10.215.137.129]
INFO:   negotiation complete
INFO:   negotiation complete
Mon Sep 16 15:10:51 2019 : local  IP address 172.28.133.28
Mon Sep 16 15:10:51 2019 : remote IP address 192.0.2.1
Mon Sep 16 15:10:51 2019 : primary   DNS address 10.215.137.194
Mon Sep 16 15:10:51 2019 : secondary DNS address 10.215.137.129
Mon Sep 16 15:10:51 2019 : Committed PPP store
Mon Sep 16 15:10:51 2019 : Committed PPP store
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
add host 195.76.89.2: gateway en0
delete net 0.0.0.0: gateway 192.168.1.1
add net 0.0.0.0: gateway ppp0
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.
INFO:   Cancelling threads...
INFO:   Setting ppp interface down.
INFO:   Restoring routes...
delete host 195.76.89.2: gateway en0
delete net 0.0.0.0: gateway ppp0
add net 0.0.0.0: gateway 192.168.1.1
INFO:   Removing VPN nameservers...
Mon Sep 16 15:11:12 2019 : Hangup (SIGHUP)
Mon Sep 16 15:11:12 2019 : Modem hangup
Mon Sep 16 15:11:12 2019 : Connection terminated.
Mon Sep 16 15:11:12 2019 : LCP close (User request).
Mon Sep 16 15:11:12 2019 : Connect time 0.4 minutes.
Mon Sep 16 15:11:12 2019 : Sent 57138 bytes, received 1376 bytes.
INFO:   pppd: The link was terminated by the modem hanging up.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.

You can also find the verbose output and ppp output at:
- [openfortivpn.log](https://github.com/adrienverge/openfortivpn/files/3616426/openfortivpn.log)
- [pppd.log](https://github.com/adrienverge/openfortivpn/files/3616427/pppd.log)

Accessing the same VPN with the same command works when connecting from a Centos 7 box, therefore this issues seems to be OS related.

Is this some known behavior? Might it be related to the OSX pppd implementation?
I haven't find anything similar on the other reported issues.

Thanks!

**Comment by mrbaseman** [comment] 2019-09-16 15:41
I believe _openfortivpn_ fails to detect your network topology correctly. It removes the route to your gateway 192.168.1.1 and adds a host route over en0, but probably you have to tell it somehow that the gateway 192.168.1.1 shall be used for this traffic. 
You could try using the `--half-internet-routes=1` option which switches to a mode that avoids removing the default route for sending the traffic through the tunnel.

**Comment by madrover** [comment] 2019-09-16 16:06
Thanks for your prompt reply, @mrbaseman !
Unfortunately that switch hasn't helped...

It is certainly true that the network layout is much simpler in the Linux VM that in my mac laptop and that might be causing issues.

Here's the current setup on my mac, if that's helpful.

```
$ ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
XHC20: flags=0<> mtu 0
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether f4:5c:89:92:a0:eb
	inet6 fe80::14b6:9db2:558c:11df%en0 prefixlen 64 secured scopeid 0x5
	inet 192.168.1.118 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	ether 06:5c:89:92:a0:eb
	media: autoselect
	status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	ether ae:fb:69:81:6b:6e
	inet6 fe80::acfb:69ff:fe81:6b6e%awdl0 prefixlen 64 scopeid 0x7
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
en1: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=60<TSO4,TSO6>
	ether 6a:00:01:91:ef:70
	media: autoselect <full-duplex>
	status: inactive
en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=60<TSO4,TSO6>
	ether 6a:00:01:91:ef:71
	media: autoselect <full-duplex>
	status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 6a:00:01:91:ef:70
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 8 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 9 priority 0 path cost 0
	nd6 options=201<PERFORMNUD,DAD>
	media: <unknown type>
	status: inactive
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::8cd2:d5c:1338:b27d%utun0 prefixlen 64 scopeid 0xb
	nd6 options=201<PERFORMNUD,DAD>
gpd0: flags=8862<BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1400
	ether 02:50:41:00:01:01
	inet 10.145.27.86 netmask 0xffffffff broadcast 10.145.27.86
vboxnet0: flags=8842<BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:00
vboxnet1: flags=8842<BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:01
vboxnet2: flags=8842<BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:02
vboxnet3: flags=8842<BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:03
vboxnet4: flags=8842<BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:04
vboxnet5: flags=8842<BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:05
vboxnet6: flags=8842<BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:06
en4: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 6e:8d:c1:b2:a5:c7
	inet6 fe80::1cac:4e8a:c1d4:c2cf%en4 prefixlen 64 secured scopeid 0x15
	inet 169.254.207.213 netmask 0xffff0000 broadcast 169.254.255.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (100baseTX <full-duplex>)
	status: active
$ netstat -nr
netstat -nr
Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            192.168.1.1        UGSc          120        0     en0
127                127.0.0.1          UCS             0        0     lo0
127.0.0.1          127.0.0.1          UH              8    47192     lo0
169.254            link#5             UCS             3        0     en0      !
169.254            link#21            UCSI            1        0     en4      !
169.254.181.108    6e:8d:c1:b2:a5:c5  UHLSW           0        3     en4     54
169.254.207.213/32 link#21            UCS             0        0     en4      !
169.254.255.255    link#5             UHLSW           1       25     en0      !
192.168.1          link#5             UCS             8        0     en0      !
192.168.1.1/32     link#5             UCS             1        0     en0      !
192.168.1.1        84:aa:9c:8d:d7:a9  UHLWIir        49      158     en0   1193
192.168.1.2        2c:b0:5d:39:8f:af  UHLWI           0        0     en0    394
192.168.1.6        b8:27:eb:21:18:8a  UHLWIi          7     1595     en0   1158
192.168.1.10       0:d:a2:1:48:2c     UHLWIi          3   860727     en0    454
192.168.1.105      6c:8d:c1:b2:a5:38  UHLWIi          1      179     en0     54
192.168.1.118/32   link#5             UCS             1        0     en0      !
192.168.1.118      f4:5c:89:92:a0:eb  UHLWI           0       74     lo0
192.168.1.120      0:23:df:81:33:ac   UHLWIi          1     1564     en0     50
192.168.1.130      0:24:36:eb:8b:63   UHLWI           0       34     en0   1175
192.168.1.193      b0:34:95:d:8d:45   UHLWIi          3       84     en0   1198
192.168.1.255      ff:ff:ff:ff:ff:ff  UHLWbI          0        5     en0      !
224.0.0/4          link#5             UmCS            2        0     en0      !
224.0.0/4          link#21            UmCSI           1        0     en4      !
224.0.0.251        1:0:5e:0:0:fb      UHmLWI          0        0     en0
239.255.255.250    1:0:5e:7f:ff:fa    UHmLWI          0      821     en0
239.255.255.250    1:0:5e:7f:ff:fa    UHmLWI          0      235     en4
255.255.255.255/32 link#5             UCS             0        0     en0      !
255.255.255.255/32 link#21            UCSI            0        0     en4      !

Internet6:
Destination                             Gateway                         Flags         Netif Expire
default                                 fe80::%utun0                    UGcI          utun0
::1                                     ::1                             UHL             lo0
fe80::%lo0/64                           fe80::1%lo0                     UcI             lo0
fe80::1%lo0                             link#1                          UHLI            lo0
fe80::%en0/64                           link#5                          UCI             en0
fe80::499:bf4d:e85:7041%en0             6c:8d:c1:b2:a5:38               UHLWIi          en0
fe80::14b6:9db2:558c:11df%en0           f4:5c:89:92:a0:eb               UHLI            lo0
fe80::1caf:795d:6a28:4a92%en0           b0:34:95:d:8d:45                UHLWI           en0
fe80::86aa:9cff:fe8d:d7a9%en0           84:aa:9c:8d:d7:a9               UHLWI           en0
fe80::%awdl0/64                         link#7                          UCI           awdl0
fe80::acfb:69ff:fe81:6b6e%awdl0         ae:fb:69:81:6b:6e               UHLI            lo0
fe80::%utun0/64                         fe80::8cd2:d5c:1338:b27d%utun0  UcI           utun0
fe80::8cd2:d5c:1338:b27d%utun0          link#11                         UHLI            lo0
fe80::%en4/64                           link#21                         UCI             en4
fe80::1476:7a01:8573:25cd%en4           6e:8d:c1:b2:a5:c5               UHLWI           en4
fe80::1cac:4e8a:c1d4:c2cf%en4           6e:8d:c1:b2:a5:c7               UHLI            lo0
ff01::%lo0/32                           ::1                             UmCI            lo0
ff01::%en0/32                           link#5                          UmCI            en0
ff01::%awdl0/32                         link#7                          UmCI          awdl0
ff01::%utun0/32                         fe80::8cd2:d5c:1338:b27d%utun0  UmCI          utun0
ff01::%en4/32                           link#21                         UmCI            en4
ff02::%lo0/32                           ::1                             UmCI            lo0
ff02::%en0/32                           link#5                          UmCI            en0
ff02::%awdl0/32                         link#7                          UmCI          awdl0
ff02::%utun0/32                         fe80::8cd2:d5c:1338:b27d%utun0  UmCI          utun0
ff02::%en4/32                           link#21                         UmCI            en4
```

**Comment by mrbaseman** [comment] 2019-09-16 21:26
there are concurrent routes over `en0` and `en4`. Perhaps if you add a host route to the vpn gateway before starting _openfortivpn_ helps to keep the connection running. If that works I have to think how to detect this situation and set up the correct routing automatically.

**Comment by madrover** [comment] 2019-09-17 09:56
en0 is the WLAN interface and en4 is the Ethernet adaptor, which I sometimes use. I have removed the en4 interface, now the routing table is much tidier, but the misbehavior remains:

```
netstat -nr
Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            192.168.1.1        UGSc          145       30     en0
127                127.0.0.1          UCS             0        0     lo0
127.0.0.1          127.0.0.1          UH             14    60377     lo0
169.254            link#5             UCS             1        0     en0      !
192.168.1          link#5             UCS             5        0     en0      !
192.168.1.1/32     link#5             UCS             1        0     en0      !
192.168.1.1        e0:41:36:bc:41:e9  UHLWIir        75       98     en0   1170
192.168.1.34       e0:ac:cb:98:90:fe  UHLWI           0        0     en0    845
192.168.1.41       6c:8d:c1:b2:a5:38  UHLWIi          3       92     en0    952
192.168.1.42/32    link#5             UCS             1        0     en0      !
192.168.1.42       f4:5c:89:92:a0:eb  UHLWI           0       20     lo0
192.168.1.120      link#5             UHRLWI          0       82     en0      !
192.168.1.130      link#5             UHRLWI          0       82     en0      !
192.168.1.255      ff:ff:ff:ff:ff:ff  UHLWbI          0        4     en0      !
224.0.0/4          link#5             UmCS            2        0     en0      !
224.0.0.251        1:0:5e:0:0:fb      UHmLWI          0        0     en0
239.255.255.250    1:0:5e:7f:ff:fa    UHmLWI          0      192     en0
255.255.255.255/32 link#5             UCS             0        0     en0      !

Internet6:
Destination                             Gateway                         Flags         Netif Expire
default                                 fe80::%utun0                    UGcI          utun0
::1                                     ::1                             UHL             lo0
fe80::%lo0/64                           fe80::1%lo0                     UcI             lo0
fe80::1%lo0                             link#1                          UHLI            lo0
fe80::%en0/64                           link#5                          UCI             en0
fe80::499:bf4d:e85:7041%en0             6c:8d:c1:b2:a5:38               UHLWI           en0
fe80::14b6:9db2:558c:11df%en0           f4:5c:89:92:a0:eb               UHLI            lo0
fe80::e241:36ff:febc:41e9%en0           e0:41:36:bc:41:e9               UHLWIi          en0
fe80::%awdl0/64                         link#7                          UCI           awdl0
fe80::acfb:69ff:fe81:6b6e%awdl0         ae:fb:69:81:6b:6e               UHLI            lo0
fe80::%utun0/64                         fe80::8cd2:d5c:1338:b27d%utun0  UcI           utun0
fe80::8cd2:d5c:1338:b27d%utun0          link#11                         UHLI            lo0
ff01::%lo0/32                           ::1                             UmCI            lo0
ff01::%en0/32                           link#5                          UmCI            en0
ff01::%awdl0/32                         link#7                          UmCI          awdl0
ff01::%utun0/32                         fe80::8cd2:d5c:1338:b27d%utun0  UmCI          utun0
ff02::%lo0/32                           ::1                             UmCI            lo0
ff02::%en0/32                           link#5                          UmCI            en0
ff02::%awdl0/32                         link#7                          UmCI          awdl0
ff02::%utun0/32                         fe80::8cd2:d5c:1338:b27d%utun0  UmCI          utun0
```

```
sudo openfortivpn xxxxx:10443 -u xxxxx -p xxxxxx --trusted-cert xxxxxxx --half-internet-routes=1  | ts
sep 17 11:55:22 WARN:   You should not pass the password on the command line. Type it interactively or use a config file instead.
sep 17 11:55:22 WARN:   Bad port in config file: "0".
sep 17 11:55:22 INFO:   Connected to gateway.
sep 17 11:55:23 INFO:   Authenticated.
sep 17 11:55:23 INFO:   Remote gateway has allocated a VPN.
sep 17 11:55:24 INFO:   No split VPN route
Tue Sep 17 11:55:24 2019 : publish_entry SCDSet() failed: Success!
Tue Sep 17 11:55:24 2019 : publish_entry SCDSet() failed: Success!
Tue Sep 17 11:55:24 2019 : Using interface ppp0
Tue Sep 17 11:55:24 2019 : Connect: ppp0 <--> /dev/ttys007
sep 17 11:55:24 INFO:   Got addresses: [172.28.133.27], ns [10.215.137.194, 10.215.137.129]
sep 17 11:55:24 INFO:   negotiation complete
sep 17 11:55:24 INFO:   negotiation complete
Tue Sep 17 11:55:24 2019 : local  IP address 172.28.133.27
Tue Sep 17 11:55:24 2019 : remote IP address 192.0.2.1
Tue Sep 17 11:55:24 2019 : primary   DNS address 10.215.137.194
Tue Sep 17 11:55:24 2019 : secondary DNS address 10.215.137.129
Tue Sep 17 11:55:24 2019 : Committed PPP store
Tue Sep 17 11:55:24 2019 : Committed PPP store
sep 17 11:55:24 INFO:   Interface ppp0 is UP.
sep 17 11:55:24 INFO:   Setting new routes...
sep 17 11:55:24 add host 195.76.89.2: gateway en0
sep 17 11:55:24 add net 0.0.0.0: gateway ppp0
sep 17 11:55:24 add net 128.0.0.0: gateway ppp0
sep 17 11:55:24 INFO:   Adding VPN nameservers...
sep 17 11:55:24 INFO:   Tunnel is up and running.
sep 17 11:55:45 INFO:   Cancelling threads...
sep 17 11:55:45 INFO:   Setting ppp interface down.
sep 17 11:55:45 INFO:   Restoring routes...
sep 17 11:55:45 delete host 195.76.89.2: gateway en0
sep 17 11:55:45 INFO:   Removing VPN nameservers...
Tue Sep 17 11:55:45 2019 : Hangup (SIGHUP)
Tue Sep 17 11:55:45 2019 : Modem hangup
Tue Sep 17 11:55:45 2019 : Connection terminated.
Tue Sep 17 11:55:45 2019 : LCP close (User request).
Tue Sep 17 11:55:45 2019 : Connect time 0.4 minutes.
Tue Sep 17 11:55:45 2019 : Sent 33528 bytes, received 2230 bytes.
sep 17 11:55:45 INFO:   pppd: The link was terminated by the modem hanging up.
sep 17 11:55:45 INFO:   Terminated pppd.
sep 17 11:55:45 INFO:   Closed connection to gateway.
sep 17 11:55:45 INFO:   Logged out.
```

**Comment by mrbaseman** [comment] 2019-09-18 15:38
For the host route it should set the gateway ip instead of the en0 interface. The gateway ip is parsed from the netstat output from the line of the default route. I haven't found an explanation yet, why this doesn't work in your case.
Did you try to set the host route manually, before calling _openfortivpn_ ? That might be a workaround until we find the root cause why the route detection doesn't work as expected here.

**Comment by madrover** [comment] 2019-09-18 15:54
I just tried to add the VPN server route manually with the following command, but that didn't work.

```
sudo route add -host 195.76.89.2 -interface en0
```

Actually, setting that route was preventing me to even initiate the VPN connection.

Maybe I am not setting the right route?

**Comment by mrbaseman** [comment] 2019-09-18 16:46
Instead of `-interface en0` you should have appended the gateway ip `192.168.1.1`.
You have done exactly what _openfortivpn_ is doing by mistake ;)

**Comment by madrover** [comment] 2019-09-19 07:49
Gotcha!  So, if I understand it well, the issue is that openfortivpn does not detect correctly the gateway and then sets the routing incorrectly, right?

Unfortunately adding the proposed static route didn't work, though... :(

See:

```
$ netstat -nr
Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            172.22.4.253       UGSc          124      194     en0
127                127.0.0.1          UCS             0        0     lo0
127.0.0.1          127.0.0.1          UH             19   201676     lo0
169.254            link#5             UCS             1        0     en0      !
172.22.4/23        link#5             UCS             7        0     en0      !
172.22.4.1         34:17:eb:ed:9:b7   UHLWIi          9      770     en0   1130
172.22.4.240       20:a6:cd:c4:ee:be  UHLWI           0        0     en0   1195
172.22.4.253       c0:ea:e4:65:2d:1c  UHLWIir        22        2     en0   1186
172.22.5.9         70:70:d:29:de:b8   UHLWI           0        0     en0    996
172.22.5.10        60:3:8:a3:ec:4     UHLWI           0        0     en0    950
172.22.5.13        40:a8:f0:b6:46:7d  UHLWI           0       22     en0    944
172.22.5.21/32     link#5             UCS             0        0     en0      !
224.0.0/4          link#5             UmCS            2        0     en0      !
224.0.0.251        1:0:5e:0:0:fb      UHmLWI          0        0     en0
239.255.255.250    1:0:5e:7f:ff:fa    UHmLWI          0       62     en0
255.255.255.255/32 link#5             UCS             0        0     en0      !

Internet6:
Destination                             Gateway                         Flags         Netif Expire
default                                 fe80::%utun0                    UGcI          utun0
::1                                     ::1                             UHL             lo0
fe80::%lo0/64                           fe80::1%lo0                     UcI             lo0
fe80::1%lo0                             link#1                          UHLI            lo0
fe80::%en0/64                           link#5                          UCI             en0
fe80::14b6:9db2:558c:11df%en0           f4:5c:89:92:a0:eb               UHLI            lo0
fe80::%awdl0/64                         link#7                          UCI           awdl0
fe80::acfb:69ff:fe81:6b6e%awdl0         ae:fb:69:81:6b:6e               UHLI            lo0
fe80::%utun0/64                         fe80::8cd2:d5c:1338:b27d%utun0  UcI           utun0
fe80::8cd2:d5c:1338:b27d%utun0          link#11                         UHLI            lo0
ff01::%lo0/32                           ::1                             UmCI            lo0
ff01::%en0/32                           link#5                          UmCI            en0
ff01::%awdl0/32                         link#7                          UmCI          awdl0
ff01::%utun0/32                         fe80::8cd2:d5c:1338:b27d%utun0  UmCI          utun0
ff02::%lo0/32                           ::1                             UmCI            lo0
ff02::%en0/32                           link#5                          UmCI            en0
ff02::%awdl0/32                         link#7                          UmCI          awdl0
ff02::%utun0/32                         fe80::8cd2:d5c:1338:b27d%utun0  UmCI          utun0
$ sudo route add -host 172.22.4.253 -interface en0
add host 172.22.4.253: gateway en0
$ unbuffer sudo openfortivpn -c config -v  | grep -v bytes
DEBUG:  openfortivpn 1.10.0
DEBUG:  Loaded config file "config".
DEBUG:  Config host = "xxxxxxxxxx"
DEBUG:  Config realm = ""
DEBUG:  Config port = "10443"
DEBUG:  Config username = "xxxxxxxx"
DEBUG:  Resolving gateway host ip
DEBUG:  Establishing ssl connection
DEBUG:  server_addr: 195.76.89.2
DEBUG:  server_port: 10443
DEBUG:  gateway_addr: 195.76.89.2
DEBUG:  gateway_port: 10443
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Connected to gateway.
DEBUG:  Cookie: SVPNCOOKIE=qDxq28RBzj23Epixpx2UXUpjFpqES8KlGLi0myBv1X7CEnGy0+He4D45UgkfbTrJ%0aya/GxUTTGIoj73OIGzEzlRfZWuK49cqhUNdG/7M48+2yQpYOQuG2dhVyv/rO9qsw%0aZN75jPy2rkXP4Ihc5V7UJQ==%0a
INFO:   Authenticated.
DEBUG:  Cookie: SVPNCOOKIE=qDxq28RBzj23Epixpx2UXUpjFpqES8KlGLi0myBv1X7CEnGy0+He4D45UgkfbTrJ%0aya/GxUTTGIoj73OIGzEzlRfZWuK49cqhUNdG/7M48+2yQpYOQuG2dhVyv/rO9qsw%0aZN75jPy2rkXP4Ihc5V7UJQ==%0a
INFO:   Remote gateway has allocated a VPN.
DEBUG:  server_addr: 195.76.89.2
DEBUG:  server_port: 10443
DEBUG:  gateway_addr: 195.76.89.2
DEBUG:  gateway_port: 10443
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
DEBUG:  Retrieving configuration
INFO:   No split VPN route
DEBUG:  Establishing the tunnel
DEBUG:  ppp_path: /usr/sbin/pppd
DEBUG:  Switch to tunneling mode
DEBUG:  Starting IO through the tunnel
DEBUG:  pppd_read thread
DEBUG:  ssl_read thread
DEBUG:  ssl_write thread
DEBUG:  if_config thread
Thu Sep 19 09:34:42 2019 : publish_entry SCDSet() failed: Success!
Thu Sep 19 09:34:42 2019 : publish_entry SCDSet() failed: Success!
Thu Sep 19 09:34:42 2019 : Using interface ppp0
Thu Sep 19 09:34:42 2019 : Connect: ppp0 <--> /dev/ttys004
DEBUG:  pppd_write thread
INFO:   Got addresses: [172.28.133.28], ns [10.215.137.194, 10.215.137.129]
INFO:   negotiation complete
DEBUG:  Got Address: 172.28.133.28
DEBUG:  if_config: not ready yet...
DEBUG:  Got Address: 172.28.133.28
DEBUG:  if_config: not ready yet...
INFO:   negotiation complete
Thu Sep 19 09:34:44 2019 : local  IP address 172.28.133.28
Thu Sep 19 09:34:44 2019 : remote IP address 192.0.2.1
Thu Sep 19 09:34:44 2019 : primary   DNS address 10.215.137.194
Thu Sep 19 09:34:44 2019 : secondary DNS address 10.215.137.129
Thu Sep 19 09:34:44 2019 : Committed PPP store
Thu Sep 19 09:34:44 2019 : Committed PPP store
DEBUG:  Got Address: 172.28.133.28
DEBUG:  Interface Name: ppp0
DEBUG:  Interface Addr: 172.28.133.28
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
DEBUG:  ip route show to 0.0.0.0/0.0.0.0 dev !ppp0
DEBUG:  netstat_path: /usr/sbin/netstat
DEBUG:  ip route show to 195.76.89.2/255.255.255.255 dev ppp0
DEBUG:  netstat_path: /usr/sbin/netstat
DEBUG:  ip route show to 224.0.0.0/0.0.0.240 dev !ppp0
DEBUG:  netstat_path: /usr/sbin/netstat
DEBUG:  Setting route to vpn server...
DEBUG:  ip route show to 195.76.89.2/255.255.255.255 dev en0
DEBUG:  /sbin/route -n add -host 195.76.89.2 -interface en0
add host 195.76.89.2: gateway en0
DEBUG:  Setting new half-internet routes...
DEBUG:  /sbin/route -n add -net 0.0.0.0 -netmask 128.0.0.0 -interface ppp0
add net 0.0.0.0: gateway ppp0
DEBUG:  /sbin/route -n add -net 128.0.0.0 -netmask 128.0.0.0 -interface ppp0
add net 128.0.0.0: gateway ppp0
INFO:   Adding VPN nameservers...
DEBUG:  Adding "nameserver 10.215.137.194" and "nameserver 10.215.137.129" to /etc/resolv.conf.
INFO:   Tunnel is up and running.
DEBUG:  Error writing to SSL connection (Connection closed).
DEBUG:  Error reading from SSL connection (Operation timed out).
INFO:   Cancelling threads...
DEBUG:  disconnecting
INFO:   Setting ppp interface down.
INFO:   Restoring routes...
DEBUG:  /sbin/route -n delete -host 195.76.89.2 -interface en0
delete host 195.76.89.2: gateway en0
INFO:   Removing VPN nameservers...
DEBUG:  Deleting "nameserver 10.215.137.194" from /etc/resolv.conf.
DEBUG:  Deleting "nameserver 10.215.137.129" from /etc/resolv.conf.
DEBUG:  Waiting for pppd to exit...
Thu Sep 19 09:35:28 2019 : Hangup (SIGHUP)
Thu Sep 19 09:35:28 2019 : Modem hangup
Thu Sep 19 09:35:28 2019 : Connection terminated.
Thu Sep 19 09:35:28 2019 : LCP close (User request).
Thu Sep 19 09:35:28 2019 : Connect time 0.8 minutes.
DEBUG:  waitpid: pppd exit status code 16
INFO:   pppd: The link was terminated by the modem hanging up.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
DEBUG:  server_addr: 195.76.89.2
DEBUG:  server_port: 10443
DEBUG:  gateway_addr: 195.76.89.2
DEBUG:  gateway_port: 10443
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Logged out.
```

**Comment by mrbaseman** [comment] 2019-09-19 10:29
no. It should have been
`$ sudo route add -host 195.76.89.2 172.22.4.253`
this time, and yesterday you had the gateway 192.168.1.1, so yesterday it would have been
`$ sudo route add -host 195.76.89.2 192.168.1.1`
Normally, _openfortivpn_ should parse the netstat output and find out the appropriate route (in your case it's the default route) how to reach the vpn server. It should detect either the interface or, if it is a route that has a gateway set (like it is the case for your default route), it should pick up that gateway and add a host route that is responsible to reach the vpn server when the routes are configured that it receives from the remote side through the vpn.

**Comment by mrbaseman** [comment] 2019-09-19 15:00
@madrover I believe I have found the problem:

There was a bug in the code that has parsed the netstat output (which is only needed on MAC and BSD). It was in the part that handles the routing entries with CIDR notation. The bit mask that was calculated was just shifted in the wrong direction. It affects only entries that have a mask different from /32 and it also was only relevant when several routes existed, for which the same network address came out of the masking process when this wrong bitmask was used. 

In your case the multicast address with /4 mask was the problem, and the netmask has returned the most significant 4 bits instead of the last significant bits (the problem is that for the masking process the reversed(!) bit order is relevant). If the mask is /32 anyway, it makes no difference, and for smaller networks, like /24 we have enough other bits that by chance wouldn't match. Some other cases, where the correct route is not the default route, may have been affected by this bug, too, but these are probably rather exotic scenarios.

Could you try my [cidrfix branch](https://github.com/mrbaseman/openfortivpn/tree/cidrfix) please

**Comment by mrbaseman** [comment] 2019-09-19 20:11
I have updated my cidrfix-Branch, see #471

**Comment by madrover** [comment] 2019-09-19 20:31
great news! that fixed the issue!

Thanks for you help, @mrbaseman :smiley:

**Comment by mrbaseman** [comment] 2019-09-19 22:15
I have merged this into the current master. It will be in the next release.

**Closed by mrbaseman** 2019-09-19 22:15 UTC

**Comment by mrbaseman** [comment] 2019-11-28 21:27
This fix went into the [1.11.0 Release](https://github.com/adrienverge/openfortivpn/releases/tag/v1.11.0).

**Comment by jbrtn** [comment] 2022-02-07 22:19
I appear to be having this same issue on macOS Monterey 12.1

Was the fix confirmed to be working for you @madrover

**Comment by madrover** [comment] 2022-02-08 10:39
As per previous comment, I think so.
However, it's been years since I've used this software so I can't provide further insights...
